package codegen

import (
	"strings"

	"github.com/F33D3R-Inc/fct/internal/ast"
)

// rustBackend targets Rust: snake_case fields, a public struct per facet for the
// typed data, and Rust infix expressions. The render body is the neutral IR —
// see backend.go. This is the target the original public spec named (DECISIONS.md
// ADR-0001), now reachable through the same compiler core.
type rustBackend struct{}

func init() { backends["rust"] = rustBackend{} }

func (rustBackend) Name() string { return "rust" }

// FieldName is identity: FDL field names are already valid snake_case Rust
// identifiers.
func (rustBackend) FieldName(field string) string { return field }

func (rustBackend) Expr(expr string, scope []string) (string, error) {
	n, err := parseExpr(expr, scope)
	if err != nil {
		return "", err
	}
	return renderInfix(n, infixStyle{
		data:    "data",
		field:   func(s string) string { return s },
		logical: nil, // Rust uses &&/||/! as-is
		boolLit: func(s string) string { return s },
		call:    func(recv string, args []string) string { return recv + "(" + strings.Join(args, ", ") + ")" },
	}), nil
}

func (rustBackend) Types(pkg string, facets []*ast.Facet) string {
	var b strings.Builder
	b.WriteString("// Code generated by fct. DO NOT EDIT.\n")
	for _, f := range facets {
		inputs := inputFields(f)
		if len(inputs) == 0 {
			continue
		}
		b.WriteString("\n#[derive(Debug, Clone)]\npub struct " + f.Name + "Data {\n")
		for _, fld := range inputs {
			b.WriteString("    pub " + fld.Name + ": " + rustType(fld.Type) + ",\n")
		}
		b.WriteString("}\n")
	}
	return b.String()
}

func (rustBackend) TypesFile() string { return "types.rs" }

func rustType(t string) string {
	switch t {
	case "int":
		return "i64"
	case "float":
		return "f64"
	case "str":
		return "String"
	case "bool":
		return "bool"
	default:
		return t // custom domain type (app-provided)
	}
}
