package codegen

import (
	"strings"

	"github.com/F33D3R-Inc/fct/internal/ast"
)

// nodeBackend targets Node.js / TypeScript: camelCase identifiers, TS interfaces
// for the typed data, and JS infix expressions. The render body is the neutral
// IR (the target runtime interprets it), so this backend supplies only the
// language-specific lowering — see backend.go.
type nodeBackend struct{}

func init() { backends["node"] = nodeBackend{} }

func (nodeBackend) Name() string { return "node" }

func (nodeBackend) FieldName(field string) string { return camelName(field) }

func (nodeBackend) Expr(expr string, scope []string) (string, error) {
	n, err := parseExpr(expr, scope)
	if err != nil {
		return "", err
	}
	return renderInfix(n, infixStyle{
		data:    "data",
		field:   camelName,
		logical: nil, // JS uses &&/||/! as-is
		boolLit: func(s string) string { return s },
		call:    func(recv string, args []string) string { return recv + "(" + strings.Join(args, ", ") + ")" },
	}), nil
}

func (nodeBackend) Types(pkg string, facets []*ast.Facet) string {
	var b strings.Builder
	b.WriteString("// Code generated by fct. DO NOT EDIT.\n")
	for _, f := range facets {
		inputs := inputFields(f)
		if len(inputs) == 0 {
			continue
		}
		b.WriteString("\nexport interface " + f.Name + "Data {\n")
		for _, fld := range inputs {
			b.WriteString("  " + camelName(fld.Name) + ": " + tsType(fld.Type) + ";\n")
		}
		b.WriteString("}\n")
	}
	return b.String()
}

func (nodeBackend) TypesFile() string { return "types.ts" }

func tsType(t string) string {
	switch t {
	case "int", "float":
		return "number"
	case "str":
		return "string"
	case "bool":
		return "boolean"
	default:
		return t // custom domain type (app-provided)
	}
}

// camelName maps an FDL snake_case field to a JS camelCase identifier:
// user_id → userId, avatar_url → avatarUrl, id → id.
func camelName(field string) string {
	parts := strings.Split(field, "_")
	var b strings.Builder
	first := true
	for _, p := range parts {
		if p == "" {
			continue
		}
		if first {
			b.WriteString(p)
			first = false
			continue
		}
		r := []rune(p)
		r[0] = upper(r[0])
		b.WriteString(string(r))
	}
	return b.String()
}
