package codegen

import (
	"strings"

	"github.com/F33D3R-Inc/fct/internal/ast"
)

// pyBackend targets Python: snake_case identifiers (FDL is already snake_case),
// @dataclass declarations for the typed data, and Python infix expressions with
// and/or/not and True/False. The render body is the neutral IR — see backend.go.
type pyBackend struct{}

func init() { backends["python"] = pyBackend{} }

func (pyBackend) Name() string { return "python" }

// FieldName is identity: FDL field names are already valid snake_case Python
// identifiers (user_id, avatar_url).
func (pyBackend) FieldName(field string) string { return field }

func (pyBackend) Expr(expr string, scope []string) (string, error) {
	n, err := parseExpr(expr, scope)
	if err != nil {
		return "", err
	}
	return renderInfix(n, infixStyle{
		data:    "data",
		field:   func(s string) string { return s },
		logical: map[string]string{"&&": "and", "||": "or", "!": "not"},
		boolLit: func(s string) string {
			if s == "true" {
				return "True"
			}
			return "False"
		},
		call: func(recv string, args []string) string { return recv + "(" + strings.Join(args, ", ") + ")" },
	}), nil
}

func (pyBackend) Types(pkg string, facets []*ast.Facet) string {
	var b strings.Builder
	b.WriteString("# Code generated by fct. DO NOT EDIT.\n")
	b.WriteString("from __future__ import annotations\n")
	b.WriteString("from dataclasses import dataclass\n")
	for _, f := range facets {
		inputs := inputFields(f)
		if len(inputs) == 0 {
			continue
		}
		b.WriteString("\n\n@dataclass\nclass " + f.Name + "Data:\n")
		for _, fld := range inputs {
			b.WriteString("    " + fld.Name + ": " + pyType(fld.Type) + "\n")
		}
	}
	return b.String()
}

func (pyBackend) TypesFile() string { return "types.py" }

func pyType(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "float"
	case "str":
		return "str"
	case "bool":
		return "bool"
	default:
		return t // custom domain type (app-provided)
	}
}
