// Package codegen lowers an ast.Facet into the two v0 compiler artifacts:
//
//  1. a Go html/template (one per facet) with data-facet-id injected on the
//     root element and every {expr}/Ctrl transpiled to {{...}} actions;
//  2. a manifest.json the client runtime reads to route SSE events to DOM nodes.
//
// The render node stream is flat (Text/Interp/Ctrl) and Go templates are flat
// ({{if}}...{{end}}), so emission is a single linear pass with a small opener
// stack to track loop-variable scope. See README.md, DECISIONS.md.
package codegen

import (
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/F33D3R-Inc/fct/internal/ast"
)

// Output is the result of compiling a set of facets.
type Output struct {
	Templates map[string]string // facet name → Go html/template source
	Aux       map[string]string // internal slot-fill templates (not facets)
	Manifest  []byte            // manifest.json (pretty-printed, trailing \n)
}

// TemplateFileName is the on-disk name for a facet's template artifact.
func TemplateFileName(facetName string) string { return facetName + ".tmpl.html" }

// GoStructs generates a typed Go data struct per facet from its what: block, so
// apps can render with compile-time-checked data instead of map[string]any:
//
//	type LikeButtonData struct { Post Post; Count int; Liked bool }
//	c.Render("LikeButton", LikeButtonData{Post: p, Count: 5, Liked: true})
//
// Field names are idiomatic Go (goName). Builtin types map to Go types; a custom
// type (capitalized) is referenced by name — define it (or map it via fct.toml)
// in the same package.
func GoStructs(pkg string, facets []*ast.Facet) string {
	var b strings.Builder
	b.WriteString("// Code generated by fct. DO NOT EDIT.\n\npackage " + pkg + "\n")
	for _, f := range facets {
		// Computed fields are derived at render time, not supplied by the caller,
		// so they are not part of the input struct.
		var inputs []ast.Field
		for _, fld := range f.Fields {
			if !fld.IsComputed() {
				inputs = append(inputs, fld)
			}
		}
		if len(inputs) == 0 {
			continue
		}
		b.WriteString("\n// " + f.Name + "Data is the typed data for facet " + f.Name + ".\n")
		b.WriteString("type " + f.Name + "Data struct {\n")
		for _, fld := range inputs {
			b.WriteString("\t" + GoName(fld.Name) + " " + goType(fld.Type) + "\n")
		}
		b.WriteString("}\n")
	}
	return b.String()
}

func goType(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "float64"
	case "str":
		return "string"
	case "bool":
		return "bool"
	default:
		return t // custom domain type (app-provided)
	}
}

// genCtx carries per-facet codegen state: the facet name (for naming slot-fill
// templates) and the auxiliary templates produced for block-form children.
type genCtx struct {
	facet string
	aux   map[string]string
	n     int
	// Brick 4 (docs/REACTIVITY.md) — client reactivity collected during the single
	// emit walk, so the template's data-fa-bind markers and the manifest's binding
	// ids share one source of truth and cannot drift.
	state    map[string]string // state signal name → its initial-value expression
	derived  map[string]bool   // client-derived computed field names (Brick 5)
	queries  map[string]bool   // async query names (Brick 11) — reactive {loading,error,data}
	inTag    bool              // currently between `<` and `>` (attribute context)
	bind     int               // next binding id counter
	bindings []bindingEntry    // live reactive bindings (text + attr), in document order
}

// builtinSignals are reactive roots every facet may reference without declaring
// them. `route` is the current client path (Brick 10), seeded by the runtime from
// location.pathname and updated on navigation — the wedge for a client router.
var builtinSignals = map[string]bool{"route": true}

// reactiveRoots reports whether an interpolation expression is a live client
// binding: it has at least one root and every root is a reactive value — a state
// signal (Brick 4), a client-derived value (Brick 5), an async query (Brick 11),
// or the built-in `route` (Brick 10) — so the runtime can recompute it from the
// signal store. A mix with a plain `what:` input prop stays server-rendered.
func (c *genCtx) reactiveRoots(expr string) bool {
	roots := exprRoots(expr)
	if len(roots) == 0 {
		return false
	}
	for _, r := range roots {
		if !c.isReactiveRoot(r) {
			return false
		}
	}
	return true
}

// isReactiveRoot reports whether r names a value the client can recompute.
func (c *genCtx) isReactiveRoot(r string) bool {
	if _, sig := c.state[r]; sig {
		return true
	}
	return c.derived[r] || c.queries[r] || builtinSignals[r]
}

// bakeable reports whether an expression's first paint can be computed at compile
// time: every root is a state signal (known literal initial) or a client-derived
// field (itself baked from signals at the top of the template). Such a binding is
// baked into the server template for a correct, flash-free first paint. A binding
// that touches an async query (no value until it resolves) or the route (unknown
// until load) is NOT bakeable — it is emitted neutral and corrected by the
// runtime's hydrate pass at boot.
func (c *genCtx) bakeable(expr string) bool {
	for _, r := range exprRoots(expr) {
		if _, sig := c.state[r]; sig {
			continue
		}
		if c.derived[r] {
			continue
		}
		return false
	}
	return true
}

// Generate compiles facets into templates + a manifest.
func Generate(facets []*ast.Facet) (*Output, error) {
	if err := checkComposition(facets); err != nil {
		return nil, err
	}
	if err := checkComputed(facets); err != nil {
		return nil, err
	}
	if err := checkState(facets); err != nil {
		return nil, err
	}
	if err := checkActions(facets); err != nil {
		return nil, err
	}
	if err := checkQueries(facets); err != nil {
		return nil, err
	}
	if err := checkBindValues(facets); err != nil {
		return nil, err
	}
	if err := checkFieldRefs(facets); err != nil {
		return nil, err
	}
	out := &Output{Templates: make(map[string]string, len(facets)), Aux: map[string]string{}}
	var man manifest
	for _, f := range facets {
		var bindings []bindingEntry
		var lists []listEntry
		if f.ServerRendered() {
			tmpl, aux, binds, ls, err := genTemplate(f)
			if err != nil {
				return nil, fmt.Errorf("%s %s: %w", f.KindName(), f.Name, err)
			}
			out.Templates[f.Name] = tmpl
			bindings = binds
			lists = ls
			for k, v := range aux {
				out.Aux[k] = v
			}
		} else if len(f.Looks) > 0 {
			// Structural backstop for the taxonomy's defining guarantee: a
			// client-rendered primitive (vault/media/signal) must emit ZERO server
			// template. The parser already rejects looks: on these kinds; this catches
			// any AST that slips through (so a compromised server literally cannot
			// produce vault plaintext — there is no template to render it).
			return nil, fmt.Errorf("%s %s: client-rendered primitives emit no server template (unexpected looks: body)", f.KindName(), f.Name)
		}
		man.Facets = append(man.Facets, genManifest(f, bindings, lists))
	}
	b, err := json.MarshalIndent(man, "", "  ")
	if err != nil {
		return nil, err
	}
	out.Manifest = append(b, '\n')
	return out, nil
}

// ── template generation ─────────────────────────────────────────────────────

func genTemplate(f *ast.Facet) (string, map[string]string, []bindingEntry, []listEntry, error) {
	ctx := &genCtx{facet: f.Name, aux: map[string]string{}, state: stateInit(f), derived: clientDerived(f), queries: queryNames(f)}
	// Computed fields lower to template variables defined once at the top, in
	// declaration order so a later one can use an earlier one. References to them
	// in looks resolve to $name (they are seeded into the render scope). Signals in
	// a computed expression are baked to their initial value for the first paint.
	defs, computed, err := emitComputed(f.Fields, ctx.state)
	if err != nil {
		return "", nil, nil, nil, err
	}
	// Reactive lists are lifted out before emit: each becomes an <fa-for> host the
	// runtime fills, with the loop body captured as a client item template.
	looks, lists := extractLists(f.Looks, ctx.state)
	body, err := emitNodes(looks, computed, ctx)
	if err != nil {
		return "", nil, nil, nil, err
	}
	attr, err := facetIDAttr(f)
	if err != nil {
		return "", nil, nil, nil, err
	}
	css, err := resolveStyleBlock(f.Style)
	if err != nil {
		return "", nil, nil, nil, fmt.Errorf("facet %s: %w", f.Name, err)
	}
	// Rewrite client event wirings `on:<event>="action"` to data attributes the
	// runtime delegates on (Brick 4); data-* is inert HTML, so html/template never
	// treats it as a JS-context handler. bind:value/bind:checked (Brick 9) lower the
	// same way, to data-fa-bind-value / data-fa-bind-checked markers.
	body = wireHandlerAttrs(body)
	body = wireBindAttrs(body)
	// data-facet-id and the resolved style: block both attach to the root element.
	body = injectRootStyle(injectFacetID(body, attr), css)
	return defs + body, ctx.aux, ctx.bindings, lists, nil
}

// stateInit maps each state signal to its initial-value expression — the lookup
// used to bake a signal's first paint into the server template.
func stateInit(f *ast.Facet) map[string]string {
	if len(f.State) == 0 {
		return nil
	}
	m := make(map[string]string, len(f.State))
	for _, s := range f.State {
		m[s.Name] = s.Expr
	}
	return m
}

// wireHandlerAttrs rewrites every `on:<event>="action"` (single or double quoted)
// to `data-fa-on-<event>="action"` so the runtime can find and delegate the
// handler. Event/action are identifiers (validated by checkActions).
func wireHandlerAttrs(body string) string {
	return handlerAttrRe.ReplaceAllStringFunc(body, func(m string) string {
		g := handlerAttrRe.FindStringSubmatch(m)
		action := g[2]
		if action == "" {
			action = g[3]
		}
		return `data-fa-on-` + g[1] + `="` + action + `"`
	})
}

// emitComputed lowers a facet's computed fields to `{{$name := <expr>}}` actions
// (declaration order; each may reference earlier computed fields) and returns
// the action string plus the computed field names to seed the render scope.
func emitComputed(fields []ast.Field, state map[string]string) (string, []string, error) {
	var b strings.Builder
	var names []string
	for _, fld := range fields {
		if !fld.IsComputed() {
			continue
		}
		// Bake any state signal in the expression to its initial value so the
		// first server paint matches what the client computes from the signals'
		// initial values (a no-op for signal-free, server-only computed fields).
		e, err := goExpr(substituteSignals(fld.Expr, state), names)
		if err != nil {
			return "", nil, err
		}
		b.WriteString("{{$" + fld.Name + " := " + e + "}}")
		names = append(names, fld.Name)
	}
	return b.String(), names, nil
}

// emitNodes walks the flat render stream, transpiling each node and tracking
// loop-variable scope via an opener stack so `end` can pop the right scope. The
// initial scope seeds names that resolve to $vars from the start — the facet's
// computed fields (and, for slot defaults, the enclosing loop scope).
func emitNodes(nodes []ast.Node, initial []string, ctx *genCtx) (string, error) {
	var b strings.Builder
	scope := append([]string(nil), initial...) // active $vars: computed + loop (stack)
	var forStack []bool                        // true if the matching opener was a `for`

	// Brick 8 — attribute-context binding state. When a Text chunk ends with an
	// attribute open (`class="`) immediately followed by a reactive interp, we strip
	// that `attr="` and let the interp emit a controlled, marked attribute instead;
	// skipQuote then drops the now-redundant closing `"` from the following Text, and
	// pendingMarkers carries the binding ids to inject as data-fa-bind-attr on the
	// element when its opening tag closes.
	var pendingAttr string
	var pendingMarkers []string
	skipQuote := false

	for i := 0; i < len(nodes); i++ {
		switch v := nodes[i].(type) {
		case ast.Text:
			s := v.S
			if skipQuote {
				if strings.HasPrefix(s, `"`) {
					s = s[1:]
				}
				skipQuote = false
			}
			// Inject the pending attribute markers before this tag's closing `>`.
			if len(pendingMarkers) > 0 {
				if gt := strings.IndexByte(s, '>'); gt >= 0 {
					s = s[:gt] + ` data-fa-bind-attr="` + strings.Join(pendingMarkers, " ") + `"` + s[gt:]
					pendingMarkers = nil
				}
			}
			// Detect an attribute binding opening at the tail of this chunk.
			if attr, ok := attrBindingAt(nodes, i, ctx); ok {
				m := attrOpenRe.FindString(s)
				head := s[:len(s)-len(m)]
				b.WriteString(head)
				ctx.trackTag(head)
				pendingAttr = attr
				break
			}
			b.WriteString(s)
			ctx.trackTag(s)

		case ast.Interp:
			// Brick 8 — a reactive interp that is the whole value of an attribute:
			// emit a controlled attribute (boolean attrs render present/absent; value
			// attrs render `attr="…"`) and record an attr binding the runtime patches.
			if pendingAttr != "" {
				attr := pendingAttr
				pendingAttr = ""
				id := fmt.Sprintf("b%d", ctx.bind)
				ctx.bind++
				node := "attr"
				if isBooleanAttr(attr) {
					node = "boolattr"
				}
				ctx.bindings = append(ctx.bindings, bindingEntry{
					ID: id, Signals: exprRoots(v.Expr), Expr: v.Expr, Node: node, Attr: attr,
				})
				pendingMarkers = append(pendingMarkers, id)
				skipQuote = true // the following text's leading `"` is redundant now
				if ctx.bakeable(v.Expr) {
					e, err := goExpr(substituteSignals(v.Expr, ctx.state), scope)
					if err != nil {
						return "", err
					}
					if node == "boolattr" {
						b.WriteString("{{if " + e + "}}" + attr + "{{end}}")
					} else {
						b.WriteString(attr + `="{{` + e + `}}"`)
					}
				} else if node == "attr" {
					b.WriteString(attr + `=""`) // neutral; hydrate sets it at boot
				}
				break
			}
			// A live client text binding: a text-position interp whose every root is a
			// reactive value — the runtime evaluates it from the signal store (Bricks
			// 4–5/10/11). Bake the initial value when it is known at compile time,
			// otherwise emit an empty marker the hydrate pass fills.
			if !ctx.inTag && ctx.reactiveRoots(v.Expr) {
				id := fmt.Sprintf("b%d", ctx.bind)
				ctx.bind++
				ctx.bindings = append(ctx.bindings, bindingEntry{
					ID: id, Signals: exprRoots(v.Expr), Expr: v.Expr, Node: "text",
				})
				if ctx.bakeable(v.Expr) {
					e, err := goExpr(substituteSignals(v.Expr, ctx.state), scope)
					if err != nil {
						return "", err
					}
					b.WriteString(`<span data-fa-bind="` + id + `">{{` + e + "}}</span>")
				} else {
					b.WriteString(`<span data-fa-bind="` + id + `"></span>`)
				}
				break
			}
			// A reactive interp inside a tag that is NOT a pure attribute value (e.g.
			// `class="btn {active}"`): not patchable today, so bake a static initial so
			// the first paint is valid rather than emitting a broken server reference.
			if ctx.inTag && ctx.reactiveRoots(v.Expr) {
				e, err := goExpr(substituteSignals(v.Expr, ctx.state), scope)
				if err != nil {
					return "", err
				}
				b.WriteString("{{" + e + "}}")
				break
			}
			e, err := goExpr(v.Expr, scope)
			if err != nil {
				return "", err
			}
			b.WriteString("{{" + e + "}}")

		case ast.Ctrl:
			switch v.Op {
			case "if":
				e, err := goExpr(v.Expr, scope)
				if err != nil {
					return "", err
				}
				b.WriteString("{{if " + e + "}}")
				forStack = append(forStack, false)
			case "for":
				it, err := goExpr(v.Iter, scope)
				if err != nil {
					return "", err
				}
				if v.Var == "" {
					return "", fmt.Errorf("for loop missing variable")
				}
				b.WriteString("{{range $" + v.Var + " := " + it + "}}")
				scope = append(scope, v.Var)
				forStack = append(forStack, true)
			case "else":
				b.WriteString("{{else}}")
			case "end":
				b.WriteString("{{end}}")
				if len(forStack) > 0 {
					isFor := forStack[len(forStack)-1]
					forStack = forStack[:len(forStack)-1]
					if isFor && len(scope) > 0 {
						scope = scope[:len(scope)-1]
					}
				}
			default:
				return "", fmt.Errorf("unknown control op %q", v.Op)
			}

		case ast.Child:
			call, err := emitChild(v, scope, ctx)
			if err != nil {
				return "", err
			}
			b.WriteString(call)

		case ast.Slot:
			def, err := emitNodes(v.Default, scope, ctx)
			if err != nil {
				return "", err
			}
			// Parent fill for this slot if present, else the slot's default.
			key := slotKey(v.Name)
			b.WriteString(`{{if (index . "` + key + `")}}{{index . "` + key + `"}}{{else}}` + def + `{{end}}`)

		default:
			return "", fmt.Errorf("unknown render node %T", nodes[i])
		}
	}
	return b.String(), nil
}

// walkChildren visits every ast.Child in a node stream, including those nested
// in block-form children's slot content and in slot defaults.
func walkChildren(nodes []ast.Node, fn func(ast.Child)) {
	for _, n := range nodes {
		switch v := n.(type) {
		case ast.Child:
			fn(v)
			walkChildren(v.Children, fn)
			for _, name := range sortedFillNames(v.Fills) {
				walkChildren(v.Fills[name], fn)
			}
		case ast.Slot:
			walkChildren(v.Default, fn)
		}
	}
}

// collectSlotNames returns the set of named `slot name:` insertion points a
// facet declares (the default unnamed slot is excluded — it has no name to
// match a fill against).
func collectSlotNames(nodes []ast.Node) map[string]bool {
	names := map[string]bool{}
	var walk func([]ast.Node)
	walk = func(ns []ast.Node) {
		for _, n := range ns {
			switch v := n.(type) {
			case ast.Slot:
				if v.Name != "" {
					names[v.Name] = true
				}
				walk(v.Default)
			case ast.Child:
				walk(v.Children)
				for _, name := range sortedFillNames(v.Fills) {
					walk(v.Fills[name])
				}
			}
		}
	}
	walk(nodes)
	return names
}

// checkComposition validates child-facet calls across the whole set before any
// codegen: every <Child/> must name a real facet, set only fields that facet
// declares, and the composition graph must be acyclic. A cycle (including a
// facet that includes itself) would render forever → stack-overflow DoS
// (audit H3); an unknown child or prop would otherwise fail obscurely at runtime.
func checkComposition(facets []*ast.Facet) error {
	fields := make(map[string]map[string]bool, len(facets))
	slots := make(map[string]map[string]bool, len(facets))
	for _, f := range facets {
		fs := make(map[string]bool, len(f.Fields))
		for _, fl := range f.Fields {
			fs[fl.Name] = true
		}
		fields[f.Name] = fs
		slots[f.Name] = collectSlotNames(f.RenderBody())
	}

	deps := make(map[string][]string, len(facets))
	var checkErr error
	for _, f := range facets {
		walkChildren(f.RenderBody(), func(ch ast.Child) {
			if checkErr != nil {
				return
			}
			if _, known := fields[ch.Name]; !known {
				checkErr = fmt.Errorf("facet %s: unknown child facet <%s/>", f.Name, ch.Name)
				return
			}
			for _, p := range ch.Props {
				if !fields[ch.Name][p.Name] {
					checkErr = fmt.Errorf("facet %s: <%s/> has no field %q", f.Name, ch.Name, p.Name)
					return
				}
			}
			for _, name := range sortedFillNames(ch.Fills) {
				if !slots[ch.Name][name] {
					checkErr = fmt.Errorf("facet %s: <%s/> has no slot %q (declare `slot %s:` in %s)", f.Name, ch.Name, name, name, ch.Name)
					return
				}
			}
			deps[f.Name] = append(deps[f.Name], ch.Name)
		})
		if checkErr != nil {
			return checkErr
		}
	}

	// DFS three-colour cycle detection.
	const (
		white = 0
		gray  = 1
		black = 2
	)
	color := make(map[string]int, len(facets))
	var visit func(name string, path []string) error
	visit = func(name string, path []string) error {
		color[name] = gray
		path = append(path, name)
		for _, m := range deps[name] {
			switch color[m] {
			case gray:
				return fmt.Errorf("facet composition cycle: %s", strings.Join(append(path, m), " → "))
			case white:
				if err := visit(m, path); err != nil {
					return err
				}
			}
		}
		color[name] = black
		return nil
	}
	for _, f := range facets {
		if color[f.Name] == white {
			if err := visit(f.Name, nil); err != nil {
				return err
			}
		}
	}
	return nil
}

// emitChild lowers a child-facet call to a nested Go template invocation:
//
//	<Avatar user="{user}" size="large" />
//	→ {{template "Avatar" (faData "User" .User "Size" "large")}}
//
// Keys are the child's field names, Title-cased so the child template's .User /
// .Size resolve. Expression props lower via goExpr (honoring loop scope); literal
// props are quoted strings. faData (a runtime funcmap helper) builds the child's
// data map. Because the child's template injects its own data-facet-id, the
// child's id nests inside the parent's automatically.
func emitChild(c ast.Child, scope []string, ctx *genCtx) (string, error) {
	var b strings.Builder
	b.WriteString(`{{template "` + c.Name + `" (faData`)
	for _, p := range c.Props {
		var val string
		if p.IsExpr {
			e, err := goExpr(p.Expr, scope)
			if err != nil {
				return "", err
			}
			val = e
		} else {
			val = strconv.Quote(p.Literal)
		}
		b.WriteString(" " + strconv.Quote(GoName(p.Name)) + " " + val)
	}
	// Block form: render each slot's content into an auxiliary template (executed
	// with the parent's data via faSlot) and pass it under the slot's key — the
	// default slot as "__children", named slots as "__slot_<name>". The child
	// template injects them at its matching slot:/slot name:.
	if c.Children != nil {
		body, err := emitSlotAux(c.Children, ctx)
		if err != nil {
			return "", err
		}
		b.WriteString(` "` + slotKey("") + `" (faSlot ` + strconv.Quote(body) + ` .)`)
	}
	for _, name := range sortedFillNames(c.Fills) {
		body, err := emitSlotAux(c.Fills[name], ctx)
		if err != nil {
			return "", err
		}
		b.WriteString(` "` + slotKey(name) + `" (faSlot ` + strconv.Quote(body) + ` .)`)
	}
	b.WriteString(`)}}`)
	return b.String(), nil
}

// emitSlotAux renders slot/fill content into a fresh auxiliary template and
// returns its name (for faSlot to execute with the parent's data).
func emitSlotAux(nodes []ast.Node, ctx *genCtx) (string, error) {
	ctx.n++
	auxName := fmt.Sprintf("%s\x00slot\x00%d", ctx.facet, ctx.n)
	body, err := emitNodes(nodes, nil, ctx)
	if err != nil {
		return "", err
	}
	ctx.aux[auxName] = body
	return auxName, nil
}

// slotKey is the data-map key a slot's fill is passed under. The default slot
// keeps the historical "__children"; named slots use "__slot_<name>".
func slotKey(name string) string {
	if name == "" {
		return "__children"
	}
	return "__slot_" + name
}

// sortedFillNames returns the fill names in deterministic order (codegen must be
// reproducible; map iteration order is not).
func sortedFillNames(fills map[string][]ast.Node) []string {
	if len(fills) == 0 {
		return nil
	}
	names := make([]string, 0, len(fills))
	for name := range fills {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// facetIDAttr builds the ` data-facet-id="..."` attribute, transpiling any
// {expr} holes in the id pattern (e.g. LikeButton:post:{post.id}).
func facetIDAttr(f *ast.Facet) (string, error) {
	id, err := transpileHoles(f.DerivedFacetID())
	if err != nil {
		return "", err
	}
	return ` data-facet-id="` + id + `"`, nil
}

// injectFacetID inserts attr into the root element's opening tag — at the first
// tag-closing `>` that is not inside a {{...}} action. Handles self-closing tags.
func injectFacetID(s, attr string) string {
	for i := 0; i < len(s); {
		if strings.HasPrefix(s[i:], "{{") {
			j := strings.Index(s[i:], "}}")
			if j < 0 {
				break
			}
			i += j + 2
			continue
		}
		if s[i] == '>' {
			at := i
			if i > 0 && s[i-1] == '/' {
				at = i - 1
			}
			return s[:at] + attr + s[at:]
		}
		i++
	}
	return s // no opening tag found (e.g. root is a {{...}} action) — leave as-is
}

// ── expression transpilation ────────────────────────────────────────────────

// goExpr lives in expr.go (the FDL expression compiler).

// transpileHoles rewrites every {expr} in s to {{goExpr}} (outer scope only).
func transpileHoles(s string) (string, error) {
	var b strings.Builder
	for {
		i := strings.IndexByte(s, '{')
		if i < 0 {
			b.WriteString(s)
			return b.String(), nil
		}
		b.WriteString(s[:i])
		j := strings.IndexByte(s[i:], '}')
		if j < 0 {
			return "", fmt.Errorf("unterminated '{' in %q", s)
		}
		e, err := goExpr(strings.TrimSpace(s[i+1:i+j]), nil)
		if err != nil {
			return "", err
		}
		b.WriteString("{{" + e + "}}")
		s = s[i+j+1:]
	}
}

// ── manifest ────────────────────────────────────────────────────────────────

type manifest struct {
	Facets []facetEntry `json:"facets"`
}

type facetEntry struct {
	Name    string `json:"name"`
	Kind    string `json:"kind"`
	FacetID string `json:"facet_id"`
	// Server-rendered kinds carry a Template (the html/template file); client-
	// rendered kinds (vault/media/signal) carry Client (the raw render body the
	// browser interprets) and NO template — the structural guarantee.
	Template string `json:"template,omitempty"`
	Client   string `json:"client,omitempty"`
	// Per-kind declarative extras (recorded; runtime semantics staged).
	Order    string      `json:"order,omitempty"`
	Throttle string      `json:"throttle,omitempty"`
	Window   string      `json:"window,omitempty"`
	TTL      string      `json:"ttl,omitempty"`
	States   []string    `json:"states,omitempty"`
	Who      *whoEntry   `json:"who,omitempty"`
	When     []whenEntry `json:"when"`
	// Brick 2 of docs/REACTIVITY.md — the compiled client reactive graph. State
	// lists the local signals (with initial values); Bindings records, for each
	// `{state}` interpolation, which signals feed it. The Tier-1 updater (Brick 4)
	// consumes these to patch exactly the bound DOM node when a signal changes.
	State    []stateEntry   `json:"state,omitempty"`
	Derived  []derivedEntry `json:"derived,omitempty"`
	Bindings []bindingEntry `json:"bindings,omitempty"`
	Lists    []listEntry    `json:"lists,omitempty"`
	// Brick 3 — named client actions and the DOM events wired to them. Actions are
	// the event-agnostic signal mutations; Handlers tie an element's `on:<event>`
	// to an action by name. The Tier-1 runtime (Brick 4) attaches each handler's
	// listener and runs its action's assignments, mutating the signals that
	// Bindings then flush to the DOM.
	Actions  []actionEntry  `json:"actions,omitempty"`
	Handlers []handlerEntry `json:"handlers,omitempty"`
	Effects  []effectEntry  `json:"effects,omitempty"`
	// Brick 9 — two-way input bindings (bind:value / bind:checked): the events the
	// runtime delegates to keep a signal in sync with a form control. Brick 11 —
	// async queries: server fetches the runtime exposes as reactive {loading,error,
	// data} values in the signal store.
	Inputs  []inputEntry `json:"inputs,omitempty"`
	Queries []queryEntry `json:"queries,omitempty"`
}

// stateEntry is one local reactive value (signal): its name, optional declared
// type (inferred from Init when "") and required initial value.
type stateEntry struct {
	Name string `json:"name"`
	Type string `json:"type,omitempty"`
	Init string `json:"init"`
}

// derivedEntry is one client-derived value (Brick 5): a computed `what:` field
// whose expression depends only on signals (and earlier derived values). The
// runtime recomputes Expr over the signal store, in manifest order, before
// flushing bindings.
type derivedEntry struct {
	Name string `json:"name"`
	Expr string `json:"expr"`
}

// listEntry is one reactive list (Brick 6): a `for <Var> in <Signal>` loop over a
// list-valued signal. Item is the loop body as a client template (FDL `{…}`
// syntax, rendered by the runtime's fill); the runtime keys items by id (else
// index) and reconciles the <fa-for> host's children when the signal changes.
type listEntry struct {
	ID     string `json:"id"`
	Signal string `json:"signal"`
	Var    string `json:"var"`
	Item   string `json:"item"`
}

// bindingEntry is one edge of the dependency graph: an interpolation in the
// `looks:` body and the signals that drive it. ID is a stable per-facet id in
// document order (b0, b1, …) that marker injection reuses to anchor the DOM node.
// Node is the update target kind: "text" patches a text node (Brick 4); "attr"
// sets an attribute value and "boolattr" toggles a boolean attribute's presence
// (Brick 8), with Attr naming the attribute.
type bindingEntry struct {
	ID      string   `json:"id"`
	Signals []string `json:"signals"`
	Expr    string   `json:"expr"`
	Node    string   `json:"node"`
	Attr    string   `json:"attr,omitempty"`
}

// actionEntry is one named client handler: its assignments (signal ← expr), in
// source order.
type actionEntry struct {
	Name      string        `json:"name"`
	Mutations []assignEntry `json:"mutations"`
}

type assignEntry struct {
	Target string `json:"target"`
	Expr   string `json:"expr"`
}

// handlerEntry wires a DOM event on an element to a named action. ID is a stable
// per-facet id in document order (h0, h1, …) that Brick-4 marker injection reuses
// to attach the listener to the right element.
type handlerEntry struct {
	ID     string `json:"id"`
	Event  string `json:"event"`
	Action string `json:"action"`
}

// effectEntry is one reactive side-effect (Brick 7): when any signal in Deps
// changes, the runtime runs Action (once per event cycle, no re-triggering).
type effectEntry struct {
	Deps   []string `json:"deps"`
	Action string   `json:"action"`
}

// inputEntry is one two-way form binding (Brick 9): a form control's value (Prop
// "value" or "checked") kept in sync with a state Signal. Event is the DOM event
// the runtime reads the control on ("input" for text, "change" for checkboxes).
type inputEntry struct {
	Signal string `json:"signal"`
	Prop   string `json:"prop"`
	Event  string `json:"event"`
}

// queryEntry is one async query (Brick 11): the reactive Name and the URL the
// runtime fetches into it as {loading,error,data} on mount.
type queryEntry struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

// handlerAttrRe matches an `on:<event>="<action>"` wiring attribute (single or
// double quoted) in raw looks HTML. Event and action are identifiers.
var handlerAttrRe = regexp.MustCompile(`on:([A-Za-z_]\w*)\s*=\s*(?:"([A-Za-z_]\w*)"|'([A-Za-z_]\w*)')`)

// attrOpenRe matches an attribute name and its opening quote at the END of a text
// chunk (`<button class="`) — the marker that the immediately-following interp is
// an attribute value (Brick 8). The attribute name allows HTML's `-`/`:`/`.`.
var attrOpenRe = regexp.MustCompile(`([A-Za-z_:][A-Za-z0-9_:.\-]*)="$`)

// bindAttrRe matches a `bind:value="signal"` / `bind:checked="signal"` two-way
// form binding (Brick 9). The prop is value|checked; the target is a state signal.
var bindAttrRe = regexp.MustCompile(`bind:(value|checked)\s*=\s*(?:"([A-Za-z_]\w*)"|'([A-Za-z_]\w*)')`)

// booleanAttrs are the HTML attributes whose presence (not value) is meaningful:
// a reactive binding to one toggles the attribute on/off rather than setting a
// string, so `hidden="{!visible}"` truly shows/hides and `disabled="{busy}"`
// never renders the foot-gun `disabled="false"` (which still disables).
var booleanAttrs = map[string]bool{
	"disabled": true, "checked": true, "hidden": true, "readonly": true,
	"required": true, "selected": true, "multiple": true, "open": true,
	"autofocus": true, "novalidate": true, "formnovalidate": true, "ismap": true,
	"loop": true, "muted": true, "controls": true, "default": true,
	"reversed": true, "async": true, "defer": true, "inert": true,
}

func isBooleanAttr(name string) bool { return booleanAttrs[strings.ToLower(name)] }

// attrBindingAt reports whether nodes[i] is a Text chunk that ends with an
// attribute open (`class="`) whose value is a single reactive interp (nodes[i+1])
// closed by a `"` (nodes[i+2]) — the pure-attribute-binding shape Brick 8 patches.
// A mixed value (`class="btn {x}"`) or a non-reactive interp (`href="{post.url}"`,
// server data) does not match and flows through the normal path.
func attrBindingAt(nodes []ast.Node, i int, ctx *genCtx) (string, bool) {
	t, ok := nodes[i].(ast.Text)
	if !ok || i+2 >= len(nodes) {
		return "", false
	}
	m := attrOpenRe.FindStringSubmatch(t.S)
	if m == nil {
		return "", false
	}
	interp, ok := nodes[i+1].(ast.Interp)
	if !ok || !ctx.reactiveRoots(interp.Expr) {
		return "", false
	}
	after, ok := nodes[i+2].(ast.Text)
	if !ok || !strings.HasPrefix(after.S, `"`) {
		return "", false
	}
	return m[1], true
}

// wireBindAttrs rewrites every `bind:value`/`bind:checked` to its inert data-*
// marker the runtime delegates on (Brick 9). The initial control value is set by
// the runtime's hydrate pass from the signal store, so no value is baked here.
func wireBindAttrs(body string) string {
	return bindAttrRe.ReplaceAllStringFunc(body, func(m string) string {
		g := bindAttrRe.FindStringSubmatch(m)
		sig := g[2]
		if sig == "" {
			sig = g[3]
		}
		return `data-fa-bind-` + g[1] + `="` + sig + `"`
	})
}

// scanInputs records the facet's two-way form bindings (Brick 9) for the manifest,
// in document order. A checkbox (bind:checked) is read on "change"; a text/value
// control (bind:value) on "input" for keystroke-live sync.
func scanInputs(f *ast.Facet) []inputEntry {
	var out []inputEntry
	var walk func(nodes []ast.Node)
	walk = func(nodes []ast.Node) {
		for _, n := range nodes {
			switch v := n.(type) {
			case ast.Text:
				for _, m := range bindAttrRe.FindAllStringSubmatch(v.S, -1) {
					sig := m[2]
					if sig == "" {
						sig = m[3]
					}
					prop, event := "value", "input"
					if m[1] == "checked" {
						prop, event = "checked", "change"
					}
					out = append(out, inputEntry{Signal: sig, Prop: prop, Event: event})
				}
			case ast.Slot:
				walk(v.Default)
			}
		}
	}
	walk(f.Looks)
	return out
}

// queryNames returns the set of async query names a facet declares (Brick 11),
// for use as reactive roots in bindings.
func queryNames(f *ast.Facet) map[string]bool {
	if len(f.Queries) == 0 {
		return nil
	}
	m := make(map[string]bool, len(f.Queries))
	for _, q := range f.Queries {
		m[q.Name] = true
	}
	return m
}

// genQueries records the facet's async queries (Brick 11) for the manifest.
func genQueries(f *ast.Facet) []queryEntry {
	if len(f.Queries) == 0 {
		return nil
	}
	out := make([]queryEntry, 0, len(f.Queries))
	for _, q := range f.Queries {
		out = append(out, queryEntry{Name: q.Name, URL: q.URL})
	}
	return out
}

type whoEntry struct {
	Require []string      `json:"require,omitempty"`
	Redact  []redactEntry `json:"redact,omitempty"`
}

type redactEntry struct {
	Field  string `json:"field"`
	Unless string `json:"unless,omitempty"`
}

type whenEntry struct {
	Events    []string        `json:"events"`
	Mutations []mutationEntry `json:"mutations"`
}

type mutationEntry struct {
	Op     string `json:"op"`
	Target string `json:"target,omitempty"`
	With   string `json:"with,omitempty"`
}

func genManifest(f *ast.Facet, bindings []bindingEntry, lists []listEntry) facetEntry {
	e := facetEntry{
		Name:     f.Name,
		Kind:     f.KindName(),
		FacetID:  f.DerivedFacetID(),
		Order:    f.Order,
		Throttle: f.Throttle,
		Window:   f.Window,
		TTL:      f.TTL,
		States:   f.States,
	}
	if f.ServerRendered() {
		e.Template = TemplateFileName(f.Name)
		e.State = genState(f)
		e.Derived = genDerived(f, clientDerived(f))
		e.Bindings = bindings // collected during emitNodes (shared ids)
		e.Lists = lists       // lifted out before emit
		e.Actions = genActions(f)
		e.Handlers = scanHandlers(f)
		e.Effects = genEffects(f)
		e.Inputs = scanInputs(f)
		e.Queries = genQueries(f)
	} else {
		e.Client = clientBodyText(f.Client)
	}
	if f.HasWho() {
		who := &whoEntry{Require: f.Who.Require}
		for _, r := range f.Who.Redactions {
			who.Redact = append(who.Redact, redactEntry{Field: r.Field, Unless: r.UnlessPolicy})
		}
		e.Who = who
	}
	for _, w := range f.Whens {
		we := whenEntry{Events: w.Events}
		for _, m := range w.Mutations {
			we.Mutations = append(we.Mutations, mutationEntry{Op: m.Op, Target: m.Target, With: m.With})
		}
		e.When = append(e.When, we)
	}
	return e
}

// clientDerived returns the set of computed `what:` fields that are client-derived
// (Brick 5): every root of the field's expression is a state signal or an earlier
// client-derived field, so the value can be recomputed in the browser from the
// signal store alone. A computed field that touches a plain `what:` input prop is
// server-only (it needs server data) and is not in the set. Declaration order is
// honoured, so the result is a valid evaluation order.
func clientDerived(f *ast.Facet) map[string]bool {
	if len(f.State) == 0 {
		return nil
	}
	reactive := make(map[string]bool, len(f.State))
	for _, s := range f.State {
		reactive[s.Name] = true
	}
	derived := map[string]bool{}
	for _, fl := range f.Fields {
		if !fl.IsComputed() {
			continue
		}
		roots := exprRoots(fl.Expr)
		if len(roots) == 0 {
			continue // a constant computed field never changes — not reactive
		}
		all := true
		for _, r := range roots {
			if !reactive[r] {
				all = false
				break
			}
		}
		if all {
			derived[fl.Name] = true
			reactive[fl.Name] = true // later fields may derive from this one
		}
	}
	return derived
}

// genDerived records client-derived fields for the manifest in declaration (=
// evaluation) order. The runtime computes each in turn over the signal store
// before flushing bindings.
func genDerived(f *ast.Facet, derived map[string]bool) []derivedEntry {
	if len(derived) == 0 {
		return nil
	}
	var out []derivedEntry
	for _, fl := range f.Fields {
		if fl.IsComputed() && derived[fl.Name] {
			out = append(out, derivedEntry{Name: fl.Name, Expr: fl.Expr})
		}
	}
	return out
}

// extractLists rewrites the looks stream for reactive lists (Brick 6): each
// `for <v> in <signal>` over a list-valued signal is replaced by an empty
// <fa-for> host the runtime fills, and the loop body is captured as a client item
// template. A `for` over server data (a what: field) is left as-is — it ranges on
// the server as before. Nested control inside the body is preserved in the
// captured template; a reactive list inside another reactive list is not unrolled
// here (v1 renders list items with the client fill engine, which handles nested
// plain-data {for}/{if} but not nested signals).
func extractLists(nodes []ast.Node, state map[string]string) ([]ast.Node, []listEntry) {
	var out []ast.Node
	var lists []listEntry
	for i := 0; i < len(nodes); i++ {
		c, ok := nodes[i].(ast.Ctrl)
		if !ok || c.Op != "for" {
			out = append(out, nodes[i])
			continue
		}
		if _, isSignal := state[c.Iter]; !isSignal {
			out = append(out, nodes[i]) // server-data loop — unchanged
			continue
		}
		// Reactive list: find the matching end, tracking nested if/for depth.
		depth, j := 1, i+1
		for ; j < len(nodes); j++ {
			if cc, ok := nodes[j].(ast.Ctrl); ok {
				switch cc.Op {
				case "for", "if":
					depth++
				case "end":
					depth--
				}
			}
			if depth == 0 {
				break // nodes[j] is the matching end
			}
		}
		id := fmt.Sprintf("l%d", len(lists))
		lists = append(lists, listEntry{ID: id, Signal: c.Iter, Var: c.Var, Item: clientBodyText(nodes[i+1 : j])})
		out = append(out, ast.Text{S: `<fa-for data-fa-list="` + id + `" style="display:contents"></fa-for>`})
		i = j // skip past the matching end (outer i++ advances to j+1)
	}
	return out, lists
}

// genState records the facet's local reactive values (signals) for the manifest.
// The parser guarantees every state field carries an initial value (Brick 1), so
// Init is always present.
func genState(f *ast.Facet) []stateEntry {
	if len(f.State) == 0 {
		return nil
	}
	out := make([]stateEntry, 0, len(f.State))
	for _, s := range f.State {
		out = append(out, stateEntry{Name: s.Name, Type: s.Type, Init: s.Expr})
	}
	return out
}

// trackTag advances the genCtx's "inside a tag" flag across a literal text chunk,
// so the interpolation walk can tell element text content (`>{count}<`, a live
// text binding) from attribute context (`<i class="{x}">`, not yet bindable). A
// bare `<`/`>` scan is sufficient for the looks HTML the compiler emits.
func (c *genCtx) trackTag(s string) {
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '<':
			c.inTag = true
		case '>':
			c.inTag = false
		}
	}
}

// substituteSignals rewrites a pure-signal expression for the *server's* first
// paint by replacing each signal root with its initial-value expression. The
// result contains only literals and operators, which goExpr lowers to a constant
// Go-template pipeline — so the initial render matches what the client computes
// from the signals' initial values, with no client round-trip and no flash.
func substituteSignals(expr string, state map[string]string) string {
	toks, err := exprLex(expr)
	if err != nil {
		return expr // goExpr will surface the precise error
	}
	var b strings.Builder
	for i, t := range toks {
		if i > 0 {
			b.WriteByte(' ')
		}
		if t.kind == "ident" && (i == 0 || toks[i-1].kind != "dot") {
			if init, ok := state[t.text]; ok {
				b.WriteString("(" + init + ")")
				continue
			}
		}
		b.WriteString(t.text)
	}
	return b.String()
}

// genEffects records reactive effects (Brick 7) for the manifest, in source order.
func genEffects(f *ast.Facet) []effectEntry {
	if len(f.Effects) == 0 {
		return nil
	}
	out := make([]effectEntry, 0, len(f.Effects))
	for _, e := range f.Effects {
		out = append(out, effectEntry{Deps: e.Deps, Action: e.Action})
	}
	return out
}

// genActions records the named client actions (Brick 3) for the manifest, in
// source order with their assignments. The parser guarantees each action has at
// least one mutation.
func genActions(f *ast.Facet) []actionEntry {
	if len(f.Actions) == 0 {
		return nil
	}
	out := make([]actionEntry, 0, len(f.Actions))
	for _, a := range f.Actions {
		muts := make([]assignEntry, 0, len(a.Mutations))
		for _, m := range a.Mutations {
			muts = append(muts, assignEntry{Target: m.Target, Expr: m.Expr})
		}
		out = append(out, actionEntry{Name: a.Name, Mutations: muts})
	}
	return out
}

// scanHandlers extracts `on:<event>="action"` wirings from the looks: body in
// document order, assigning each a stable id (h0, h1, …). Wirings live as raw
// HTML attributes on plain elements (a child-facet call is an ast.Child, not
// Text), so the scan reads Text nodes and slot defaults — the same scope
// genBindings uses, and it does not descend into child facets.
func scanHandlers(f *ast.Facet) []handlerEntry {
	var hs []handlerEntry
	var walk func(nodes []ast.Node)
	walk = func(nodes []ast.Node) {
		for _, n := range nodes {
			switch v := n.(type) {
			case ast.Text:
				for _, m := range handlerAttrRe.FindAllStringSubmatch(v.S, -1) {
					action := m[2]
					if action == "" {
						action = m[3] // single-quoted alternation
					}
					hs = append(hs, handlerEntry{
						ID:     fmt.Sprintf("h%d", len(hs)),
						Event:  m[1],
						Action: action,
					})
				}
			case ast.Slot:
				walk(v.Default)
			}
		}
	}
	walk(f.Looks)
	return hs
}

// clientBodyText reconstructs a client-rendered primitive's body (decrypt:/
// source:) as an FDL-shaped string for the manifest. Unlike server templates this
// is NOT lowered to html/template — it is the render description the (future)
// client runtime interprets in the browser. Storing it is safe and necessary: the
// render logic is shipped to the client anyway (like a React component); the
// secret is the runtime-encrypted data, which never appears here.
func clientBodyText(nodes []ast.Node) string {
	var b strings.Builder
	for _, n := range nodes {
		switch v := n.(type) {
		case ast.Text:
			b.WriteString(v.S)
		case ast.Interp:
			b.WriteString("{" + v.Expr + "}")
		case ast.Ctrl:
			switch v.Op {
			case "if":
				b.WriteString("{if " + v.Expr + "}")
			case "for":
				b.WriteString("{for " + v.Var + " in " + v.Iter + "}")
			case "else":
				b.WriteString("{else}")
			case "end":
				b.WriteString("{end}")
			}
		}
	}
	return b.String()
}

// ── small helpers ───────────────────────────────────────────────────────────

// goInitialisms maps lowercase words Go convention writes in all-caps.
var goInitialisms = map[string]string{
	"id": "ID", "url": "URL", "uri": "URI", "api": "API", "html": "HTML",
	"http": "HTTP", "https": "HTTPS", "json": "JSON", "xml": "XML", "sql": "SQL",
	"uuid": "UUID", "css": "CSS", "db": "DB", "ip": "IP", "tcp": "TCP",
	"udp": "UDP", "tls": "TLS", "ssh": "SSH", "ui": "UI", "cpu": "CPU", "ttl": "TTL",
}

// GoName maps an FDL field name to its idiomatic exported Go name: snake_case
// words are Title-cased and known initialisms are upper-cased — user_id → UserID,
// avatar_url → AvatarURL, id → ID, title → Title. This makes templates and data
// interop cleanly with idiomatic Go structs (fixing the old id→Id hack).
func GoName(field string) string {
	var b strings.Builder
	for _, p := range strings.Split(field, "_") {
		if p == "" {
			continue
		}
		if up, ok := goInitialisms[strings.ToLower(p)]; ok {
			b.WriteString(up)
			continue
		}
		r := []rune(p)
		r[0] = unicode.ToUpper(r[0])
		b.WriteString(string(r))
	}
	return b.String()
}

func inScope(scope []string, name string) bool {
	for _, s := range scope {
		if s == name {
			return true
		}
	}
	return false
}
