// Package codegen lowers an ast.Facet into the two v0 compiler artifacts:
//
//  1. a Go html/template (one per facet) with data-facet-id injected on the
//     root element and every {expr}/Ctrl transpiled to {{...}} actions;
//  2. a manifest.json the client runtime reads to route SSE events to DOM nodes.
//
// The render node stream is flat (Text/Interp/Ctrl) and Go templates are flat
// ({{if}}...{{end}}), so emission is a single linear pass with a small opener
// stack to track loop-variable scope. See README.md, DECISIONS.md.
package codegen

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/F33D3R-Inc/fct/internal/ast"
)

// Output is the result of compiling a set of facets.
type Output struct {
	Templates map[string]string // facet name → Go html/template source
	Aux       map[string]string // internal slot-fill templates (not facets)
	Manifest  []byte            // manifest.json (pretty-printed, trailing \n)
}

// TemplateFileName is the on-disk name for a facet's template artifact.
func TemplateFileName(facetName string) string { return facetName + ".tmpl.html" }

// GoStructs generates a typed Go data struct per facet from its what: block, so
// apps can render with compile-time-checked data instead of map[string]any:
//
//	type LikeButtonData struct { Post Post; Count int; Liked bool }
//	c.Render("LikeButton", LikeButtonData{Post: p, Count: 5, Liked: true})
//
// Field names are idiomatic Go (goName). Builtin types map to Go types; a custom
// type (capitalized) is referenced by name — define it (or map it via fct.toml)
// in the same package.
func GoStructs(pkg string, facets []*ast.Facet) string {
	var b strings.Builder
	b.WriteString("// Code generated by fct. DO NOT EDIT.\n\npackage " + pkg + "\n")
	for _, f := range facets {
		// Computed fields are derived at render time, not supplied by the caller,
		// so they are not part of the input struct.
		var inputs []ast.Field
		for _, fld := range f.Fields {
			if !fld.IsComputed() {
				inputs = append(inputs, fld)
			}
		}
		if len(inputs) == 0 {
			continue
		}
		b.WriteString("\n// " + f.Name + "Data is the typed data for facet " + f.Name + ".\n")
		b.WriteString("type " + f.Name + "Data struct {\n")
		for _, fld := range inputs {
			b.WriteString("\t" + GoName(fld.Name) + " " + goType(fld.Type) + "\n")
		}
		b.WriteString("}\n")
	}
	return b.String()
}

func goType(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "float64"
	case "str":
		return "string"
	case "bool":
		return "bool"
	default:
		return t // custom domain type (app-provided)
	}
}

// genCtx carries per-facet codegen state: the facet name (for naming slot-fill
// templates) and the auxiliary templates produced for block-form children.
type genCtx struct {
	facet string
	aux   map[string]string
	n     int
}

// Generate compiles facets into templates + a manifest.
func Generate(facets []*ast.Facet) (*Output, error) {
	if err := checkComposition(facets); err != nil {
		return nil, err
	}
	if err := checkComputed(facets); err != nil {
		return nil, err
	}
	if err := checkFieldRefs(facets); err != nil {
		return nil, err
	}
	out := &Output{Templates: make(map[string]string, len(facets)), Aux: map[string]string{}}
	var man manifest
	for _, f := range facets {
		if f.ServerRendered() {
			tmpl, aux, err := genTemplate(f)
			if err != nil {
				return nil, fmt.Errorf("%s %s: %w", f.KindName(), f.Name, err)
			}
			out.Templates[f.Name] = tmpl
			for k, v := range aux {
				out.Aux[k] = v
			}
		} else if len(f.Looks) > 0 {
			// Structural backstop for the taxonomy's defining guarantee: a
			// client-rendered primitive (vault/media/signal) must emit ZERO server
			// template. The parser already rejects looks: on these kinds; this catches
			// any AST that slips through (so a compromised server literally cannot
			// produce vault plaintext — there is no template to render it).
			return nil, fmt.Errorf("%s %s: client-rendered primitives emit no server template (unexpected looks: body)", f.KindName(), f.Name)
		}
		man.Facets = append(man.Facets, genManifest(f))
	}
	b, err := json.MarshalIndent(man, "", "  ")
	if err != nil {
		return nil, err
	}
	out.Manifest = append(b, '\n')
	return out, nil
}

// ── template generation ─────────────────────────────────────────────────────

func genTemplate(f *ast.Facet) (string, map[string]string, error) {
	ctx := &genCtx{facet: f.Name, aux: map[string]string{}}
	// Computed fields lower to template variables defined once at the top, in
	// declaration order so a later one can use an earlier one. References to them
	// in looks resolve to $name (they are seeded into the render scope).
	defs, computed, err := emitComputed(f.Fields)
	if err != nil {
		return "", nil, err
	}
	body, err := emitNodes(f.Looks, computed, ctx)
	if err != nil {
		return "", nil, err
	}
	attr, err := facetIDAttr(f)
	if err != nil {
		return "", nil, err
	}
	css, err := resolveStyleBlock(f.Style)
	if err != nil {
		return "", nil, fmt.Errorf("facet %s: %w", f.Name, err)
	}
	// data-facet-id and the resolved style: block both attach to the root element.
	body = injectRootStyle(injectFacetID(body, attr), css)
	return defs + body, ctx.aux, nil
}

// emitComputed lowers a facet's computed fields to `{{$name := <expr>}}` actions
// (declaration order; each may reference earlier computed fields) and returns
// the action string plus the computed field names to seed the render scope.
func emitComputed(fields []ast.Field) (string, []string, error) {
	var b strings.Builder
	var names []string
	for _, fld := range fields {
		if !fld.IsComputed() {
			continue
		}
		e, err := goExpr(fld.Expr, names)
		if err != nil {
			return "", nil, err
		}
		b.WriteString("{{$" + fld.Name + " := " + e + "}}")
		names = append(names, fld.Name)
	}
	return b.String(), names, nil
}

// emitNodes walks the flat render stream, transpiling each node and tracking
// loop-variable scope via an opener stack so `end` can pop the right scope. The
// initial scope seeds names that resolve to $vars from the start — the facet's
// computed fields (and, for slot defaults, the enclosing loop scope).
func emitNodes(nodes []ast.Node, initial []string, ctx *genCtx) (string, error) {
	var b strings.Builder
	scope := append([]string(nil), initial...) // active $vars: computed + loop (stack)
	var forStack []bool                         // true if the matching opener was a `for`

	for _, n := range nodes {
		switch v := n.(type) {
		case ast.Text:
			b.WriteString(v.S)

		case ast.Interp:
			e, err := goExpr(v.Expr, scope)
			if err != nil {
				return "", err
			}
			b.WriteString("{{" + e + "}}")

		case ast.Ctrl:
			switch v.Op {
			case "if":
				e, err := goExpr(v.Expr, scope)
				if err != nil {
					return "", err
				}
				b.WriteString("{{if " + e + "}}")
				forStack = append(forStack, false)
			case "for":
				it, err := goExpr(v.Iter, scope)
				if err != nil {
					return "", err
				}
				if v.Var == "" {
					return "", fmt.Errorf("for loop missing variable")
				}
				b.WriteString("{{range $" + v.Var + " := " + it + "}}")
				scope = append(scope, v.Var)
				forStack = append(forStack, true)
			case "else":
				b.WriteString("{{else}}")
			case "end":
				b.WriteString("{{end}}")
				if len(forStack) > 0 {
					isFor := forStack[len(forStack)-1]
					forStack = forStack[:len(forStack)-1]
					if isFor && len(scope) > 0 {
						scope = scope[:len(scope)-1]
					}
				}
			default:
				return "", fmt.Errorf("unknown control op %q", v.Op)
			}

		case ast.Child:
			call, err := emitChild(v, scope, ctx)
			if err != nil {
				return "", err
			}
			b.WriteString(call)

		case ast.Slot:
			def, err := emitNodes(v.Default, scope, ctx)
			if err != nil {
				return "", err
			}
			// Parent fill for this slot if present, else the slot's default.
			key := slotKey(v.Name)
			b.WriteString(`{{if (index . "` + key + `")}}{{index . "` + key + `"}}{{else}}` + def + `{{end}}`)

		default:
			return "", fmt.Errorf("unknown render node %T", n)
		}
	}
	return b.String(), nil
}

// walkChildren visits every ast.Child in a node stream, including those nested
// in block-form children's slot content and in slot defaults.
func walkChildren(nodes []ast.Node, fn func(ast.Child)) {
	for _, n := range nodes {
		switch v := n.(type) {
		case ast.Child:
			fn(v)
			walkChildren(v.Children, fn)
			for _, name := range sortedFillNames(v.Fills) {
				walkChildren(v.Fills[name], fn)
			}
		case ast.Slot:
			walkChildren(v.Default, fn)
		}
	}
}

// collectSlotNames returns the set of named `slot name:` insertion points a
// facet declares (the default unnamed slot is excluded — it has no name to
// match a fill against).
func collectSlotNames(nodes []ast.Node) map[string]bool {
	names := map[string]bool{}
	var walk func([]ast.Node)
	walk = func(ns []ast.Node) {
		for _, n := range ns {
			switch v := n.(type) {
			case ast.Slot:
				if v.Name != "" {
					names[v.Name] = true
				}
				walk(v.Default)
			case ast.Child:
				walk(v.Children)
				for _, name := range sortedFillNames(v.Fills) {
					walk(v.Fills[name])
				}
			}
		}
	}
	walk(nodes)
	return names
}

// checkComposition validates child-facet calls across the whole set before any
// codegen: every <Child/> must name a real facet, set only fields that facet
// declares, and the composition graph must be acyclic. A cycle (including a
// facet that includes itself) would render forever → stack-overflow DoS
// (audit H3); an unknown child or prop would otherwise fail obscurely at runtime.
func checkComposition(facets []*ast.Facet) error {
	fields := make(map[string]map[string]bool, len(facets))
	slots := make(map[string]map[string]bool, len(facets))
	for _, f := range facets {
		fs := make(map[string]bool, len(f.Fields))
		for _, fl := range f.Fields {
			fs[fl.Name] = true
		}
		fields[f.Name] = fs
		slots[f.Name] = collectSlotNames(f.RenderBody())
	}

	deps := make(map[string][]string, len(facets))
	var checkErr error
	for _, f := range facets {
		walkChildren(f.RenderBody(), func(ch ast.Child) {
			if checkErr != nil {
				return
			}
			if _, known := fields[ch.Name]; !known {
				checkErr = fmt.Errorf("facet %s: unknown child facet <%s/>", f.Name, ch.Name)
				return
			}
			for _, p := range ch.Props {
				if !fields[ch.Name][p.Name] {
					checkErr = fmt.Errorf("facet %s: <%s/> has no field %q", f.Name, ch.Name, p.Name)
					return
				}
			}
			for _, name := range sortedFillNames(ch.Fills) {
				if !slots[ch.Name][name] {
					checkErr = fmt.Errorf("facet %s: <%s/> has no slot %q (declare `slot %s:` in %s)", f.Name, ch.Name, name, name, ch.Name)
					return
				}
			}
			deps[f.Name] = append(deps[f.Name], ch.Name)
		})
		if checkErr != nil {
			return checkErr
		}
	}

	// DFS three-colour cycle detection.
	const (
		white = 0
		gray  = 1
		black = 2
	)
	color := make(map[string]int, len(facets))
	var visit func(name string, path []string) error
	visit = func(name string, path []string) error {
		color[name] = gray
		path = append(path, name)
		for _, m := range deps[name] {
			switch color[m] {
			case gray:
				return fmt.Errorf("facet composition cycle: %s", strings.Join(append(path, m), " → "))
			case white:
				if err := visit(m, path); err != nil {
					return err
				}
			}
		}
		color[name] = black
		return nil
	}
	for _, f := range facets {
		if color[f.Name] == white {
			if err := visit(f.Name, nil); err != nil {
				return err
			}
		}
	}
	return nil
}

// emitChild lowers a child-facet call to a nested Go template invocation:
//
//	<Avatar user="{user}" size="large" />
//	→ {{template "Avatar" (faData "User" .User "Size" "large")}}
//
// Keys are the child's field names, Title-cased so the child template's .User /
// .Size resolve. Expression props lower via goExpr (honoring loop scope); literal
// props are quoted strings. faData (a runtime funcmap helper) builds the child's
// data map. Because the child's template injects its own data-facet-id, the
// child's id nests inside the parent's automatically.
func emitChild(c ast.Child, scope []string, ctx *genCtx) (string, error) {
	var b strings.Builder
	b.WriteString(`{{template "` + c.Name + `" (faData`)
	for _, p := range c.Props {
		var val string
		if p.IsExpr {
			e, err := goExpr(p.Expr, scope)
			if err != nil {
				return "", err
			}
			val = e
		} else {
			val = strconv.Quote(p.Literal)
		}
		b.WriteString(" " + strconv.Quote(GoName(p.Name)) + " " + val)
	}
	// Block form: render each slot's content into an auxiliary template (executed
	// with the parent's data via faSlot) and pass it under the slot's key — the
	// default slot as "__children", named slots as "__slot_<name>". The child
	// template injects them at its matching slot:/slot name:.
	if c.Children != nil {
		body, err := emitSlotAux(c.Children, ctx)
		if err != nil {
			return "", err
		}
		b.WriteString(` "` + slotKey("") + `" (faSlot ` + strconv.Quote(body) + ` .)`)
	}
	for _, name := range sortedFillNames(c.Fills) {
		body, err := emitSlotAux(c.Fills[name], ctx)
		if err != nil {
			return "", err
		}
		b.WriteString(` "` + slotKey(name) + `" (faSlot ` + strconv.Quote(body) + ` .)`)
	}
	b.WriteString(`)}}`)
	return b.String(), nil
}

// emitSlotAux renders slot/fill content into a fresh auxiliary template and
// returns its name (for faSlot to execute with the parent's data).
func emitSlotAux(nodes []ast.Node, ctx *genCtx) (string, error) {
	ctx.n++
	auxName := fmt.Sprintf("%s\x00slot\x00%d", ctx.facet, ctx.n)
	body, err := emitNodes(nodes, nil, ctx)
	if err != nil {
		return "", err
	}
	ctx.aux[auxName] = body
	return auxName, nil
}

// slotKey is the data-map key a slot's fill is passed under. The default slot
// keeps the historical "__children"; named slots use "__slot_<name>".
func slotKey(name string) string {
	if name == "" {
		return "__children"
	}
	return "__slot_" + name
}

// sortedFillNames returns the fill names in deterministic order (codegen must be
// reproducible; map iteration order is not).
func sortedFillNames(fills map[string][]ast.Node) []string {
	if len(fills) == 0 {
		return nil
	}
	names := make([]string, 0, len(fills))
	for name := range fills {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// facetIDAttr builds the ` data-facet-id="..."` attribute, transpiling any
// {expr} holes in the id pattern (e.g. LikeButton:post:{post.id}).
func facetIDAttr(f *ast.Facet) (string, error) {
	id, err := transpileHoles(f.DerivedFacetID())
	if err != nil {
		return "", err
	}
	return ` data-facet-id="` + id + `"`, nil
}

// injectFacetID inserts attr into the root element's opening tag — at the first
// tag-closing `>` that is not inside a {{...}} action. Handles self-closing tags.
func injectFacetID(s, attr string) string {
	for i := 0; i < len(s); {
		if strings.HasPrefix(s[i:], "{{") {
			j := strings.Index(s[i:], "}}")
			if j < 0 {
				break
			}
			i += j + 2
			continue
		}
		if s[i] == '>' {
			at := i
			if i > 0 && s[i-1] == '/' {
				at = i - 1
			}
			return s[:at] + attr + s[at:]
		}
		i++
	}
	return s // no opening tag found (e.g. root is a {{...}} action) — leave as-is
}

// ── expression transpilation ────────────────────────────────────────────────

// goExpr lives in expr.go (the FDL expression compiler).

// transpileHoles rewrites every {expr} in s to {{goExpr}} (outer scope only).
func transpileHoles(s string) (string, error) {
	var b strings.Builder
	for {
		i := strings.IndexByte(s, '{')
		if i < 0 {
			b.WriteString(s)
			return b.String(), nil
		}
		b.WriteString(s[:i])
		j := strings.IndexByte(s[i:], '}')
		if j < 0 {
			return "", fmt.Errorf("unterminated '{' in %q", s)
		}
		e, err := goExpr(strings.TrimSpace(s[i+1:i+j]), nil)
		if err != nil {
			return "", err
		}
		b.WriteString("{{" + e + "}}")
		s = s[i+j+1:]
	}
}

// ── manifest ────────────────────────────────────────────────────────────────

type manifest struct {
	Facets []facetEntry `json:"facets"`
}

type facetEntry struct {
	Name    string `json:"name"`
	Kind    string `json:"kind"`
	FacetID string `json:"facet_id"`
	// Server-rendered kinds carry a Template (the html/template file); client-
	// rendered kinds (vault/media/signal) carry Client (the raw render body the
	// browser interprets) and NO template — the structural guarantee.
	Template string `json:"template,omitempty"`
	Client   string `json:"client,omitempty"`
	// Per-kind declarative extras (recorded; runtime semantics staged).
	Order    string      `json:"order,omitempty"`
	Throttle string      `json:"throttle,omitempty"`
	Window   string      `json:"window,omitempty"`
	TTL      string      `json:"ttl,omitempty"`
	States   []string    `json:"states,omitempty"`
	Who      *whoEntry   `json:"who,omitempty"`
	When     []whenEntry `json:"when"`
}

type whoEntry struct {
	Require []string      `json:"require,omitempty"`
	Redact  []redactEntry `json:"redact,omitempty"`
}

type redactEntry struct {
	Field  string `json:"field"`
	Unless string `json:"unless,omitempty"`
}

type whenEntry struct {
	Events    []string        `json:"events"`
	Mutations []mutationEntry `json:"mutations"`
}

type mutationEntry struct {
	Op     string `json:"op"`
	Target string `json:"target,omitempty"`
	With   string `json:"with,omitempty"`
}

func genManifest(f *ast.Facet) facetEntry {
	e := facetEntry{
		Name:     f.Name,
		Kind:     f.KindName(),
		FacetID:  f.DerivedFacetID(),
		Order:    f.Order,
		Throttle: f.Throttle,
		Window:   f.Window,
		TTL:      f.TTL,
		States:   f.States,
	}
	if f.ServerRendered() {
		e.Template = TemplateFileName(f.Name)
	} else {
		e.Client = clientBodyText(f.Client)
	}
	if f.HasWho() {
		who := &whoEntry{Require: f.Who.Require}
		for _, r := range f.Who.Redactions {
			who.Redact = append(who.Redact, redactEntry{Field: r.Field, Unless: r.UnlessPolicy})
		}
		e.Who = who
	}
	for _, w := range f.Whens {
		we := whenEntry{Events: w.Events}
		for _, m := range w.Mutations {
			we.Mutations = append(we.Mutations, mutationEntry{Op: m.Op, Target: m.Target, With: m.With})
		}
		e.When = append(e.When, we)
	}
	return e
}

// clientBodyText reconstructs a client-rendered primitive's body (decrypt:/
// source:) as an FDL-shaped string for the manifest. Unlike server templates this
// is NOT lowered to html/template — it is the render description the (future)
// client runtime interprets in the browser. Storing it is safe and necessary: the
// render logic is shipped to the client anyway (like a React component); the
// secret is the runtime-encrypted data, which never appears here.
func clientBodyText(nodes []ast.Node) string {
	var b strings.Builder
	for _, n := range nodes {
		switch v := n.(type) {
		case ast.Text:
			b.WriteString(v.S)
		case ast.Interp:
			b.WriteString("{" + v.Expr + "}")
		case ast.Ctrl:
			switch v.Op {
			case "if":
				b.WriteString("{if " + v.Expr + "}")
			case "for":
				b.WriteString("{for " + v.Var + " in " + v.Iter + "}")
			case "else":
				b.WriteString("{else}")
			case "end":
				b.WriteString("{end}")
			}
		}
	}
	return b.String()
}

// ── small helpers ───────────────────────────────────────────────────────────

// goInitialisms maps lowercase words Go convention writes in all-caps.
var goInitialisms = map[string]string{
	"id": "ID", "url": "URL", "uri": "URI", "api": "API", "html": "HTML",
	"http": "HTTP", "https": "HTTPS", "json": "JSON", "xml": "XML", "sql": "SQL",
	"uuid": "UUID", "css": "CSS", "db": "DB", "ip": "IP", "tcp": "TCP",
	"udp": "UDP", "tls": "TLS", "ssh": "SSH", "ui": "UI", "cpu": "CPU", "ttl": "TTL",
}

// GoName maps an FDL field name to its idiomatic exported Go name: snake_case
// words are Title-cased and known initialisms are upper-cased — user_id → UserID,
// avatar_url → AvatarURL, id → ID, title → Title. This makes templates and data
// interop cleanly with idiomatic Go structs (fixing the old id→Id hack).
func GoName(field string) string {
	var b strings.Builder
	for _, p := range strings.Split(field, "_") {
		if p == "" {
			continue
		}
		if up, ok := goInitialisms[strings.ToLower(p)]; ok {
			b.WriteString(up)
			continue
		}
		r := []rune(p)
		r[0] = unicode.ToUpper(r[0])
		b.WriteString(string(r))
	}
	return b.String()
}

func inScope(scope []string, name string) bool {
	for _, s := range scope {
		if s == name {
			return true
		}
	}
	return false
}
