package runtime

// More targets — native mobile clients that read the same IR. The IR is the
// product; a runtime is just an executor over it, and a mobile app is one more
// executor. `facet generate <app.fct> [outdir]` emits typed client SDKs —
// Swift (iOS), Kotlin (Android), and TypeScript (React Native / web) — straight
// from the compiled graph: a model per entity and a call per server action,
// talking to the `/api` projection the web server already serves. No hand-written
// client code, and the schema can never drift from the server because both are
// generated from one IR.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"facet/internal/ir"
)

// GenerateMobile writes the mobile client SDKs for a compiled app into dir,
// creating it if needed. It returns the paths written. The generated clients
// cover the same surface the JSON API exposes: list/read every entity and invoke
// every server-placed action (the reserved credential table and client-only
// actions are omitted, exactly as in `GET /api`).
func GenerateMobile(graph *ir.IR, dir string) ([]string, error) {
	if dir == "" {
		dir = "mobile"
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	ents := publicEntities(graph)
	acts := publicActions(graph)

	files := map[string]string{
		"Facet.swift":      swiftClient(graph, ents, acts),
		"Facet.kt":         kotlinClient(graph, ents, acts),
		"facetClient.ts":   tsClient(graph, ents, acts),
		"README.md":        mobileReadme(graph),
	}
	var written []string
	for name, content := range files {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			return written, err
		}
		written = append(written, p)
	}
	return written, nil
}

// publicEntities is every entity a client may read — all but the reserved tables.
func publicEntities(graph *ir.IR) []ir.Entity {
	var out []ir.Entity
	for _, e := range graph.Entities {
		if !isReservedEntity(e.Name) {
			out = append(out, e)
		}
	}
	return out
}

// publicActions is every server-placed action a client may invoke, the same set
// the API schema advertises.
func publicActions(graph *ir.IR) []ir.Action {
	var out []ir.Action
	for _, a := range graph.Actions {
		if a.Placement == ir.Server {
			out = append(out, a)
		}
	}
	return out
}

// ── Swift ─────────────────────────────────────────────────────────────────────

func swiftType(f ir.Field) string {
	switch {
	case f.IsRelation() || f.Type == "int" || f.Type == "money" || f.Type == "date":
		return "Int"
	case f.Type == "bool":
		return "Bool"
	default:
		return "String"
	}
}

func swiftClient(graph *ir.IR, ents []ir.Entity, acts []ir.Action) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by facet — %s. Do not edit by hand.\n", graph.App)
	b.WriteString("import Foundation\n\n")
	for _, e := range ents {
		fmt.Fprintf(&b, "public struct %s: Codable, Identifiable {\n    public let id: Int\n", e.Name)
		for _, f := range e.Fields {
			if f.Name == "id" {
				continue
			}
			fmt.Fprintf(&b, "    public var %s: %s\n", f.Name, swiftType(f))
		}
		b.WriteString("}\n\n")
	}
	b.WriteString("public final class FacetClient {\n")
	b.WriteString("    let baseURL: URL\n    let session: URLSession\n")
	b.WriteString("    public init(baseURL: URL, session: URLSession = .shared) { self.baseURL = baseURL; self.session = session }\n\n")
	b.WriteString("    struct ActionResult: Codable { let ok: Bool? }\n\n")
	b.WriteString("    private func get<T: Decodable>(_ path: String) async throws -> T {\n")
	b.WriteString("        let (data, _) = try await session.data(from: baseURL.appendingPathComponent(path))\n")
	b.WriteString("        return try JSONDecoder().decode(T.self, from: data)\n    }\n\n")
	b.WriteString("    private func post(_ path: String, _ args: [Any]) async throws {\n")
	b.WriteString("        var req = URLRequest(url: baseURL.appendingPathComponent(path))\n")
	b.WriteString("        req.httpMethod = \"POST\"\n        req.setValue(\"application/json\", forHTTPHeaderField: \"Content-Type\")\n")
	b.WriteString("        req.httpBody = try JSONSerialization.data(withJSONObject: [\"args\": args])\n")
	b.WriteString("        _ = try await session.data(for: req)\n    }\n\n")
	for _, e := range ents {
		fmt.Fprintf(&b, "    struct %sList: Codable { let rows: [%s] }\n", e.Name, e.Name)
		fmt.Fprintf(&b, "    public func list%s() async throws -> [%s] { try await get(\"api/%s\").rows }\n",
			e.Name, e.Name, e.Name)
		// wrap the response type
	}
	b.WriteString("\n")
	for _, a := range acts {
		params := swiftParams(a.Params)
		argList := actionArgList(a.Params)
		fmt.Fprintf(&b, "    public func %s(%s) async throws { try await post(\"api/%s\", [%s]) }\n",
			a.Name, params, a.Name, argList)
	}
	b.WriteString("}\n")
	return swiftFixListReturns(b.String(), ents)
}

// swiftFixListReturns rewrites the listX helpers to decode the wrapper type
// (kept separate to keep the generator above readable).
func swiftFixListReturns(src string, ents []ir.Entity) string {
	for _, e := range ents {
		old := fmt.Sprintf("try await get(\"api/%s\").rows", e.Name)
		neu := fmt.Sprintf("(try await get(\"api/%s\") as %sList).rows", e.Name, e.Name)
		src = strings.Replace(src, old, neu, 1)
	}
	return src
}

func swiftParams(ps []ir.Param) string {
	var out []string
	for _, p := range ps {
		t := "String"
		switch p.Type {
		case "int", "money", "date":
			t = "Int"
		case "bool":
			t = "Bool"
		}
		out = append(out, fmt.Sprintf("%s: %s", p.Name, t))
	}
	return strings.Join(out, ", ")
}

func actionArgList(ps []ir.Param) string {
	var out []string
	for _, p := range ps {
		out = append(out, p.Name)
	}
	return strings.Join(out, ", ")
}

// ── Kotlin ────────────────────────────────────────────────────────────────────

func kotlinType(f ir.Field) string {
	switch {
	case f.IsRelation() || f.Type == "int" || f.Type == "money" || f.Type == "date":
		return "Long"
	case f.Type == "bool":
		return "Boolean"
	default:
		return "String"
	}
}

func kotlinClient(graph *ir.IR, ents []ir.Entity, acts []ir.Action) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by facet — %s. Do not edit by hand.\n", graph.App)
	b.WriteString("package app.facet.client\n\n")
	b.WriteString("import kotlinx.serialization.Serializable\n")
	b.WriteString("import kotlinx.serialization.json.Json\n")
	b.WriteString("import java.net.URI\nimport java.net.http.HttpClient\nimport java.net.http.HttpRequest\nimport java.net.http.HttpResponse\n\n")
	for _, e := range ents {
		b.WriteString("@Serializable\ndata class " + e.Name + "(\n    val id: Long,\n")
		for _, f := range e.Fields {
			if f.Name == "id" {
				continue
			}
			fmt.Fprintf(&b, "    val %s: %s,\n", f.Name, kotlinType(f))
		}
		b.WriteString(")\n\n")
	}
	b.WriteString("class FacetClient(private val baseUrl: String) {\n")
	b.WriteString("    private val http = HttpClient.newHttpClient()\n")
	b.WriteString("    private val json = Json { ignoreUnknownKeys = true }\n\n")
	b.WriteString("    @Serializable private data class Rows<T>(val rows: List<T>)\n\n")
	b.WriteString("    private fun postAction(action: String, args: List<String>) {\n")
	b.WriteString("        val body = \"{\\\"args\\\":[\" + args.joinToString(\",\") + \"]}\"\n")
	b.WriteString("        val req = HttpRequest.newBuilder(URI.create(\"$baseUrl/api/$action\"))\n")
	b.WriteString("            .header(\"Content-Type\", \"application/json\")\n")
	b.WriteString("            .POST(HttpRequest.BodyPublishers.ofString(body)).build()\n")
	b.WriteString("        http.send(req, HttpResponse.BodyHandlers.ofString())\n    }\n\n")
	for _, a := range acts {
		var params, args []string
		for _, p := range a.Params {
			params = append(params, fmt.Sprintf("%s: String", p.Name))
			args = append(args, fmt.Sprintf("\"\\\"$%s\\\"\"", p.Name))
		}
		fmt.Fprintf(&b, "    fun %s(%s) = postAction(\"%s\", listOf(%s))\n",
			a.Name, strings.Join(params, ", "), a.Name, strings.Join(args, ", "))
	}
	b.WriteString("}\n")
	return b.String()
}

// ── TypeScript (React Native / web) ────────────────────────────────────────────

func tsType(f ir.Field) string {
	switch {
	case f.IsRelation() || f.Type == "int" || f.Type == "money" || f.Type == "date":
		return "number"
	case f.Type == "bool":
		return "boolean"
	default:
		return "string"
	}
}

func tsClient(graph *ir.IR, ents []ir.Entity, acts []ir.Action) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by facet — %s. Do not edit by hand.\n\n", graph.App)
	for _, e := range ents {
		fmt.Fprintf(&b, "export interface %s {\n  id: number;\n", e.Name)
		for _, f := range e.Fields {
			if f.Name == "id" {
				continue
			}
			fmt.Fprintf(&b, "  %s: %s;\n", f.Name, tsType(f))
		}
		b.WriteString("}\n\n")
	}
	b.WriteString("export class FacetClient {\n")
	b.WriteString("  constructor(private baseUrl: string) {}\n\n")
	b.WriteString("  private async list<T>(entity: string): Promise<T[]> {\n")
	b.WriteString("    const res = await fetch(`${this.baseUrl}/api/${entity}`, { credentials: 'include' });\n")
	b.WriteString("    return (await res.json()).rows as T[];\n  }\n\n")
	b.WriteString("  private async action(name: string, args: any[]): Promise<any> {\n")
	b.WriteString("    const res = await fetch(`${this.baseUrl}/api/${name}`, {\n")
	b.WriteString("      method: 'POST', credentials: 'include',\n")
	b.WriteString("      headers: { 'Content-Type': 'application/json' },\n")
	b.WriteString("      body: JSON.stringify({ args }),\n    });\n")
	b.WriteString("    if (!res.ok) throw new Error(await res.text());\n    return res.json();\n  }\n\n")
	for _, e := range ents {
		fmt.Fprintf(&b, "  list%s() { return this.list<%s>('%s'); }\n", e.Name, e.Name, e.Name)
	}
	b.WriteString("\n")
	for _, a := range acts {
		var params, args []string
		for _, p := range a.Params {
			params = append(params, fmt.Sprintf("%s: %s", p.Name, tsParamType(p)))
			args = append(args, p.Name)
		}
		fmt.Fprintf(&b, "  %s(%s) { return this.action('%s', [%s]); }\n",
			a.Name, strings.Join(params, ", "), a.Name, strings.Join(args, ", "))
	}
	b.WriteString("}\n")
	return b.String()
}

func tsParamType(p ir.Param) string {
	switch p.Type {
	case "int", "money", "date":
		return "number"
	case "bool":
		return "boolean"
	default:
		return "string"
	}
}

func mobileReadme(graph *ir.IR) string {
	return fmt.Sprintf(`# %s — generated mobile clients

These SDKs are generated from the compiled Facet IR and talk to the running
server's JSON API (the same `+"`/api`"+` projection the web app uses). Regenerate
them whenever the app changes:

    facet generate app.fct mobile

## Files

- `+"`Facet.swift`"+`    — iOS / macOS client (URLSession, async/await).
- `+"`Facet.kt`"+`       — Android client (java.net.http, kotlinx.serialization).
- `+"`facetClient.ts`"+` — React Native / web client (fetch).

## Use (TypeScript)

    import { FacetClient } from './facetClient';
    const api = new FacetClient('https://your-host');
    const rows = await api.list%s();

Authentication rides the session cookie (the clients send credentials); for a
native client, drive the same `+"`/api`"+` login the web app uses. Every model and
call here was generated — never edit these files by hand.
`, graph.App, firstEntityName(graph))
}

func firstEntityName(graph *ir.IR) string {
	for _, e := range graph.Entities {
		if !isReservedEntity(e.Name) {
			return e.Name
		}
	}
	return "Entity"
}
