package selfhost

// fabric_frontdoor.fct — the transparent front door in fct — against the real
// Rust front door (fabric-facetql's frontdoor.rs/proxy.rs).
//
// Two kinds of check:
//
//   - The pure decisions (answers_agree, the routing-failure table, the
//     credential, Backend::new, resolve_once, frame_end, hop-by-hop headers),
//     one input at a time: answers_agree's verdicts come from
//     testdata/frontdoor/rust_transcript.jsonl, printed by the real crate
//     (/tmp/claude-1000/team5/frontdoor/rust — a scratch binary linking
//     fabric-facetql by path, run over testdata/frontdoor/agree.json); the rest
//     port the Rust unit tests input for input.
//
//   - The server, live: for every scenario in testdata/frontdoor/scenarios.json
//     (tests/front_door.rs, test for test, plus the rest of the status table,
//     hop-by-hop headers and the body limit), the fct door runs as a real
//     daemon on a real port in front of two FacetQL-shaped Go servers, routing
//     driven by the ported table/migration/replication, and every response and
//     every request each backend saw must equal what the same step produced
//     through the Rust FrontDoor (the transcript, generated by the same scratch
//     binary over the same scenario file). Backend base URLs are normalized to
//     {a}/{b}; a transport error's own wording (reqwest's vs the fct runtime's)
//     is compared up to "did not answer: ".

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"sort"
	"strings"
	"sync"
	"testing"
	"time"

	"facet/internal/compile"
	"facet/runtime"
)

func fdoorApp(t *testing.T) (*runtime.Server, *httptest.Server) {
	t.Helper()
	g, err := compile.File("testdata/frontdoor/fixture.fct")
	if err != nil {
		t.Fatalf("compile testdata/frontdoor/fixture.fct: %v", err)
	}
	srv, err := runtime.NewInMemory(g)
	if err != nil {
		t.Fatal(err)
	}
	ts := httptest.NewServer(srv.Handler())
	t.Cleanup(ts.Close)
	return srv, ts
}

var (
	fdoorLastMu sync.Mutex
	fdoorLast   = map[*httptest.Server]string{}
)

// fdoorCall runs one fixture action and returns fxOut.
func fdoorCall(t *testing.T, ts *httptest.Server, action string, args ...any) string {
	t.Helper()
	d := postExprJSON(t, ts, action, args...)
	fdoorLastMu.Lock()
	defer fdoorLastMu.Unlock()
	if v, ok := d["fxOut"].(string); ok {
		fdoorLast[ts] = v
	}
	return fdoorLast[ts]
}

// fdoorTranscript is the Rust front door's transcript, one JSON value a line.
func fdoorTranscript(t *testing.T) []map[string]any {
	t.Helper()
	f, err := os.Open("testdata/frontdoor/rust_transcript.jsonl")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	var out []map[string]any
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<24)
	for sc.Scan() {
		var m map[string]any
		if err := json.Unmarshal(sc.Bytes(), &m); err != nil {
			t.Fatal(err)
		}
		out = append(out, m)
	}
	return out
}

func TestFrontDoorAnswersAgreeMatchesRust(t *testing.T) {
	_, ts := fdoorApp(t)
	n := 0
	for _, line := range fdoorTranscript(t) {
		pair, ok := line["agree"].([]any)
		if !ok {
			continue
		}
		n++
		got := fdoorCall(t, ts, "fxAgree", pair[0], pair[1], pair[2], pair[3])
		if want := fmt.Sprint(line["verdict"]); got != want {
			t.Errorf("answers_agree(%d %q, %d %q) = %s, Rust says %s", int(pair[0].(float64)), pair[1], int(pair[2].(float64)), pair[3], got, want)
		}
	}
	if n < 20 {
		t.Fatalf("only %d agree cases in the transcript", n)
	}
}

// TestFrontDoorRoutingFailureStatuses ports
// every_routing_failure_has_a_status_a_client_can_act_on: every routing
// failure's status and Retry-After, and exactly one kind is a 500.
func TestFrontDoorRoutingFailureStatuses(t *testing.T) {
	_, ts := fdoorApp(t)
	want := map[string]string{
		"WriteFenced":       "503|1",
		"NoWritableReplica": "503|1",
		"NoLiveOwner":       "503|1",
		"NoReadableReplica": "503|1",
		"UnknownShard":      "421|",
		"InvalidCoordinate": "421|",
		"InvalidAddress":    "400|",
		"InvalidRange":      "400|",
		"UnknownNode":       "500|",
	}
	fiveHundreds := 0
	for kind, w := range want {
		got := fdoorCall(t, ts, "fxStatus", kind)
		parts := strings.SplitN(got, "|", 3)
		if parts[0]+"|"+parts[1] != w {
			t.Errorf("%s: %s, want %s", kind, got, w)
		}
		if !strings.HasPrefix(parts[2], "fabric front door: ") {
			t.Errorf("%s: body %q", kind, parts[2])
		}
		if parts[0] == "500" {
			fiveHundreds++
		}
	}
	if fiveHundreds != 1 {
		t.Fatalf("%d routing failures are a 500, want exactly one", fiveHundreds)
	}
}

// TestFrontDoorPureDecisions ports the remaining Rust unit tests: the
// credential in the header and in the SSE fallback, Backend::new, a door with
// no backends, a request spanning two backends, frame_end and hop-by-hop.
func TestFrontDoorPureDecisions(t *testing.T) {
	_, ts := fdoorApp(t)
	for _, c := range []struct {
		headers  string
		hasQuery bool
		query    string
		want     string
	}{
		{"", false, "", "false"},
		{"", true, "key=", "false"},
		{"", true, "kind=Post&key=abc", "true"},
		{"x-api-key: t", false, "", "true"},
	} {
		if got := fdoorCall(t, ts, "fxCredential", c.headers, c.hasQuery, c.query); got != c.want {
			t.Errorf("carries_credential(%q, %v %q) = %s, want %s", c.headers, c.hasQuery, c.query, got, c.want)
		}
	}
	if got := fdoorCall(t, ts, "fxBackend", "a", "127.0.0.1:8892"); !strings.HasPrefix(got, "false|") || !strings.Contains(got, "not http(s)") {
		t.Errorf("Backend::new(127.0.0.1:8892) = %q", got)
	}
	if got := fdoorCall(t, ts, "fxBackend", "a", "http://127.0.0.1:8892/"); got != "true||http://127.0.0.1:8892" {
		t.Errorf("Backend::new(http://127.0.0.1:8892/) = %q", got)
	}
	if got := fdoorCall(t, ts, "fxNoBackends"); !strings.HasPrefix(got, "false|") || !strings.Contains(got, "no backends") {
		t.Errorf("no backends = %q", got)
	}
	spans := strings.Split(fdoorCall(t, ts, "fxSpans"), "|")
	if spans[0] != "Refuse" || spans[1] != "421" || !strings.Contains(spans[2], "operations[0] 'Post:1'") ||
		!strings.Contains(spans[2], "operations[1] 'User:2'") || !strings.Contains(spans[2], "nothing was forwarded") ||
		spans[3] != "true" || spans[4] != "db-a" {
		t.Errorf("spanning refusal = %q", spans)
	}
	for in, want := range map[string]string{
		"event: x\ndata: 1\n":    "-1",
		"event: x\ndata: 1\n\n":  "18",
		"data: 1\r\n\r\ndata: 2": "11",
	} {
		if got := fdoorCall(t, ts, "fxFrameEnd", in); got != want {
			t.Errorf("frame_end(%q) = %s, want %s", in, got, want)
		}
	}
	for name, want := range map[string]string{"Transfer-Encoding": "true", "connection": "true", "x-api-key": "false", "content-type": "false"} {
		if got := fdoorCall(t, ts, "fxHop", name); got != want {
			t.Errorf("is_hop_by_hop(%q) = %s, want %s", name, got, want)
		}
	}
}

// ── the live scenarios ──────────────────────────────────────────────────

// fdoorRecordedHeaders are the request headers a fake backend records — the
// scratch Rust binary's RECORDED_HEADERS.
var fdoorRecordedHeaders = []string{"x-api-key", "content-type", "x-custom", "proxy-authorization", "keep-alive", "te", "proxy-authenticate", "cookie"}

// fdoorFake is a FacetQL-shaped backend that records what it was asked: the
// Go twin of the Rust test's `Fake`.
type fdoorFake struct {
	name   string
	srv    *httptest.Server
	mu     sync.Mutex
	log    []any
	status int
	body   string
	frames []string
	ends   bool
	events bool
}

func fdoorNewFake(name string) *fdoorFake {
	f := &fdoorFake{name: name, status: 200, body: "FacetQL Online"}
	f.srv = httptest.NewServer(http.HandlerFunc(f.serve))
	return f
}

func (f *fdoorFake) serve(w http.ResponseWriter, r *http.Request) {
	body, _ := io.ReadAll(r.Body)
	headers := map[string]any{}
	for _, h := range fdoorRecordedHeaders {
		if vs := r.Header.Values(h); len(vs) > 0 {
			headers[h] = strings.Join(vs, ", ")
		}
	}
	f.mu.Lock()
	f.log = append(f.log, map[string]any{"method": r.Method, "target": r.RequestURI, "body": string(body), "headers": headers})
	status, reply, frames, ends, events := f.status, f.body, f.frames, f.ends, f.events
	f.mu.Unlock()
	if r.URL.Path == "/events" && events {
		w.Header().Set("Content-Type", "text/event-stream")
		w.WriteHeader(200)
		fl := w.(http.Flusher)
		fl.Flush()
		for _, frame := range frames {
			io.WriteString(w, frame)
			fl.Flush()
		}
		if !ends {
			<-r.Context().Done()
		}
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Fake-Node", f.name)
	w.WriteHeader(status)
	io.WriteString(w, reply)
}

func (f *fdoorFake) seen() []any {
	f.mu.Lock()
	defer f.mu.Unlock()
	return append([]any{}, f.log...)
}

func (f *fdoorFake) shutDown() {
	f.srv.CloseClientConnections()
	f.srv.Close()
}

func fdoorFreePort(t *testing.T) int {
	t.Helper()
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer ln.Close()
	return ln.Addr().(*net.TCPAddr).Port
}

// fdoorCanon is v re-serialized with sorted keys, for comparing JSON values.
func fdoorCanon(v any) string {
	b, _ := json.Marshal(v)
	var x any
	json.Unmarshal(b, &x)
	b, _ = json.Marshal(x)
	return string(b)
}

type fdoorScenario struct {
	Name  string           `json:"name"`
	Fleet string           `json:"fleet"`
	Steps []map[string]any `json:"steps"`
}

func fdoorHeaders(step map[string]any) [][2]string {
	var out [][2]string
	hs, _ := step["headers"].([]any)
	for _, h := range hs {
		p := h.([]any)
		out = append(out, [2]string{p[0].(string), p[1].(string)})
	}
	return out
}

func fdoorRequest(t *testing.T, url string, step map[string]any) *http.Request {
	t.Helper()
	var body io.Reader
	if b, ok := step["body"].(string); ok {
		body = strings.NewReader(b)
	} else if n, ok := step["body_len"].(float64); ok {
		body = strings.NewReader(strings.Repeat("a", int(n)))
	}
	req, err := http.NewRequest(step["method"].(string), url+step["path"].(string), body)
	if err != nil {
		t.Fatal(err)
	}
	for _, h := range fdoorHeaders(step) {
		req.Header.Add(h[0], h[1])
	}
	return req
}

func fdoorHeaderOrNull(h http.Header, name string) any {
	if v := h.Get(name); v != "" {
		return v
	}
	return nil
}

// fdoorFramesOf is the Rust binary's frames_of: the stream split on blank
// lines into sorted whole frames.
func fdoorFramesOf(s string) []any {
	var fs []string
	for _, f := range strings.Split(s, "\n\n") {
		if f != "" {
			fs = append(fs, f+"\n\n")
		}
	}
	sort.Strings(fs)
	out := []any{}
	for _, f := range fs {
		out = append(out, f)
	}
	return out
}

func TestFrontDoorScenariosMatchRust(t *testing.T) {
	raw, err := os.ReadFile("testdata/frontdoor/scenarios.json")
	if err != nil {
		t.Fatal(err)
	}
	var scenarios []fdoorScenario
	if err := json.Unmarshal(raw, &scenarios); err != nil {
		t.Fatal(err)
	}
	want := map[string]map[string]any{}
	for _, line := range fdoorTranscript(t) {
		if s, ok := line["scenario"].(string); ok {
			want[fmt.Sprintf("%s#%d", s, int(line["step"].(float64)))] = line
		}
	}
	checked := 0
	for _, sc := range scenarios {
		sc := sc
		t.Run(sc.Name, func(t *testing.T) {
			checked += fdoorRunScenario(t, sc, want)
		})
	}
	if checked != len(want) {
		t.Fatalf("checked %d steps, the Rust transcript has %d", checked, len(want))
	}
}

func fdoorRunScenario(t *testing.T, sc fdoorScenario, want map[string]map[string]any) int {
	a, b := fdoorNewFake("a"), fdoorNewFake("b")
	defer b.shutDown()
	defer a.shutDown()
	srv, ts := fdoorApp(t)
	port := fdoorFreePort(t)
	if err := fdoorCall(t, ts, "fxStart", sc.Fleet, port, a.srv.URL, b.srv.URL); err != "" {
		t.Fatalf("fxStart: %s", err)
	}
	srv.StartJobs()
	url := fmt.Sprintf("http://127.0.0.1:%d", port)
	deadline := time.Now().Add(5 * time.Second)
	for {
		c, err := net.Dial("tcp", fmt.Sprintf("127.0.0.1:%d", port))
		if err == nil {
			c.Close()
			break
		}
		if time.Now().After(deadline) {
			t.Fatalf("the front door never listened: %v", err)
		}
		time.Sleep(10 * time.Millisecond)
	}
	client := &http.Client{}
	defer client.CloseIdleConnections()
	fake := func(step map[string]any) *fdoorFake {
		if step["node"] == "a" {
			return a
		}
		return b
	}
	normalize := func(s string) string {
		return strings.ReplaceAll(strings.ReplaceAll(s, a.srv.URL, "{a}"), b.srv.URL, "{b}")
	}
	checked := 0
	for i, step := range sc.Steps {
		key := fmt.Sprintf("%s#%d", sc.Name, i+1)
		switch step["op"] {
		case "answers":
			f := fake(step)
			f.mu.Lock()
			f.status, f.body = int(step["status"].(float64)), step["body"].(string)
			f.mu.Unlock()
		case "emits":
			f := fake(step)
			f.mu.Lock()
			f.frames = nil
			for _, fr := range step["frames"].([]any) {
				f.frames = append(f.frames, fr.(string))
			}
			f.ends, _ = step["ends"].(bool)
			f.events = true
			f.mu.Unlock()
		case "forget":
			f := fake(step)
			f.mu.Lock()
			f.log = nil
			f.mu.Unlock()
		case "shutdown":
			fake(step).shutDown()
		case "publish":
			name := step["routing"].(string)
			if ms, ok := step["after_ms"].(float64); ok {
				time.AfterFunc(time.Duration(ms)*time.Millisecond, func() {
					http.Post(ts.URL+"/api/fxPublish", "application/json", strings.NewReader(fmt.Sprintf(`{"args":[%q]}`, name)))
				})
			} else {
				fdoorCall(t, ts, "fxPublish", name)
			}
		case "call":
			out := map[string]any{}
			resp, err := client.Do(fdoorRequest(t, url, step))
			if err != nil {
				out["error"] = err.Error()
			} else {
				body, _ := io.ReadAll(resp.Body)
				resp.Body.Close()
				out = map[string]any{
					"status":       resp.StatusCode,
					"retry_after":  fdoorHeaderOrNull(resp.Header, "Retry-After"),
					"content_type": fdoorHeaderOrNull(resp.Header, "Content-Type"),
					"x_fake_node":  fdoorHeaderOrNull(resp.Header, "X-Fake-Node"),
					"body":         normalize(string(body)),
				}
			}
			fdoorCompare(t, key, want[key], out, a.seen(), b.seen())
			checked++
		case "subscribe":
			resp, err := client.Do(fdoorRequest(t, url, step))
			if err != nil {
				t.Fatalf("%s: %v", key, err)
			}
			out := map[string]any{
				"status":        resp.StatusCode,
				"content_type":  fdoorHeaderOrNull(resp.Header, "Content-Type"),
				"cache_control": fdoorHeaderOrNull(resp.Header, "Cache-Control"),
			}
			if resp.StatusCode == 200 {
				var until []string
				for _, u := range step["until"].([]any) {
					until = append(until, u.(string))
				}
				seen, ended := fdoorReadStream(resp.Body, until)
				out["frames"] = fdoorFramesOf(seen)
				out["ended"] = ended
			} else {
				body, _ := io.ReadAll(resp.Body)
				out["body"] = normalize(string(body))
			}
			resp.Body.Close()
			fdoorCompare(t, key, want[key], out, a.seen(), b.seen())
			checked++
		default:
			t.Fatalf("unknown op %v", step["op"])
		}
	}
	return checked
}

// fdoorReadStream reads an SSE body until every `until` marker has been seen
// (or, with none, until it ends), giving up after two quiet seconds.
func fdoorReadStream(body io.Reader, until []string) (string, string) {
	type chunk struct {
		b   []byte
		err error
	}
	ch := make(chan chunk, 16)
	go func() {
		for {
			buf := make([]byte, 4096)
			n, err := body.Read(buf)
			ch <- chunk{buf[:n], err}
			if err != nil {
				return
			}
		}
	}()
	seen := ""
	done := func() bool {
		if len(until) == 0 {
			return false
		}
		for _, u := range until {
			if !strings.Contains(seen, u) {
				return false
			}
		}
		return true
	}
	for !done() {
		select {
		case c := <-ch:
			seen += string(c.b)
			if c.err == io.EOF {
				return seen, "eof"
			}
			if c.err != nil {
				return seen, "error"
			}
		case <-time.After(2 * time.Second):
			return seen, "timeout"
		}
	}
	return seen, "open"
}

// fdoorCompare checks one step against the Rust transcript: the response, and
// every request each backend has seen so far.
func fdoorCompare(t *testing.T, key string, want map[string]any, out map[string]any, aLog, bLog []any) {
	t.Helper()
	if want == nil {
		t.Errorf("%s: not in the Rust transcript", key)
		return
	}
	rustOut := want["out"].(map[string]any)
	if rb, ok := rustOut["body"].(string); ok {
		if i := strings.Index(rb, "did not answer: "); i >= 0 {
			cut := i + len("did not answer: ")
			if gb, _ := out["body"].(string); len(gb) >= cut && gb[:cut] == rb[:cut] {
				out["body"] = rb
			}
		}
	}
	if g, w := fdoorCanon(out), fdoorCanon(rustOut); g != w {
		t.Errorf("%s: response\n  fct:  %s\n  rust: %s", key, g, w)
	}
	if g, w := fdoorCanon(aLog), fdoorCanon(want["a"]); g != w {
		t.Errorf("%s: db-a saw\n  fct:  %s\n  rust: %s", key, g, w)
	}
	if g, w := fdoorCanon(bLog), fdoorCanon(want["b"]); g != w {
		t.Errorf("%s: db-b saw\n  fct:  %s\n  rust: %s", key, g, w)
	}
}
